"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { LifeBuoy, Plus, Search, Send, ArrowLeft, CheckCircle2 } from "lucide-react";
import { createSupportTicket, updateSupportTicket } from "@/app/actions/vendor-support";
import { SUPPORT_CATEGORIES, SUPPORT_STATUSES } from "@/lib/support/policy";
import s from "./support.module.css";
type Ticket={id:string;subject:string;category:string;priority:string;status:string;reference:string|null;updatedAt:string;storeName:string;messages:{id:string;body:string;authorRole:string;createdAt:string}[]};
export default function SupportCentre({tickets,selectedId,admin=false}:{tickets:Ticket[];selectedId?:string;admin?:boolean}){
 const router=useRouter();const [query,setQuery]=useState("");const [filter,setFilter]=useState("active");const [creating,setCreating]=useState(false);const [error,setError]=useState("");const [pending,start]=useTransition();
 const selected=tickets.find(t=>t.id===selectedId);const base=`/dashboard/${admin?"admin":"vendor"}/support`;
 const shown=tickets.filter(t=>(filter==="all" || (filter==="resolved"?t.status==="RESOLVED":t.status!=="RESOLVED")) && `${t.subject} ${t.reference??""} ${t.storeName}`.toLowerCase().includes(query.toLowerCase()));
 return <main className={s.page}><header className={s.hero}><div><span><LifeBuoy size={18}/> LINKWE SUPPORT</span><h1>A clear path to a solution.</h1><p>{admin?"One queue for vendor issues. Keep every update with its ticket.":"Tell us what’s happening. Follow progress and keep every reply together."}</p></div>{!admin&&<button data-tour="support-new" onClick={()=>{setCreating(true);setError("");}}><Plus size={18}/>New ticket</button>}</header>
 <div className={s.stats} data-tour="support-status">{[["Open",tickets.filter(t=>t.status==="OPEN").length],["In progress",tickets.filter(t=>t.status==="IN_PROGRESS").length],["Reply needed",tickets.filter(t=>t.status==="WAITING_VENDOR").length],["Resolved",tickets.filter(t=>t.status==="RESOLVED").length]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 {creating ? <section className={s.compose}><button className={s.back} onClick={()=>setCreating(false)}><ArrowLeft size={16}/>Back to tickets</button><h2>How can we help?</h2><p>Include what you expected, what happened and any order or listing reference. Never include passwords or card details.</p><form action={data=>start(async()=>{setError("");const result=await createSupportTicket(data);if(result.error)setError(result.error);else{setCreating(false);router.push(`${base}?ticket=${result.id}`);router.refresh();}})}><div className={s.fields}><label>Topic<select name="category">{SUPPORT_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Priority<select name="priority"><option value="NORMAL">Normal — general assistance</option><option value="HIGH">High — business blocked</option></select></label></div><label>Subject<input name="subject" maxLength={140} required placeholder="A short summary of the issue"/></label><label>Order or listing reference <small>(optional)</small><input name="reference" maxLength={100} placeholder="Copy the reference shown in your dashboard"/></label><label>What happened?<textarea name="body" required minLength={10} maxLength={5000} rows={6}/></label><button disabled={pending} className={s.primary}>{pending?"Saving…":"Submit ticket"}<Send size={16}/></button></form></section>:
 <div className={s.workspace}><aside><label className={s.search}><Search size={17}/><input aria-label="Search tickets" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subject or reference"/></label><div className={s.filters}>{["active","resolved","all"].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className={s.list}>{shown.map(t=><Link key={t.id} href={`${base}?ticket=${t.id}`} aria-current={selected?.id===t.id?"page":undefined}><span>{t.category}{t.priority==="HIGH"&&" · High priority"}</span><strong>{t.subject}</strong>{admin&&<small>{t.storeName}</small>}<small>{SUPPORT_STATUSES[t.status as keyof typeof SUPPORT_STATUSES]} · {new Date(t.updatedAt).toLocaleDateString("en-TT")}</small></Link>)}{!shown.length&&<p className={s.empty}>No tickets in this view.</p>}</div></aside>
 <section className={s.detail}>{selected?<><header><small>{selected.category} · #{selected.id.slice(-8).toUpperCase()}</small><h2>{selected.subject}</h2><p>{selected.reference?`Reference: ${selected.reference}`:"No order or listing reference"}</p><span>{SUPPORT_STATUSES[selected.status as keyof typeof SUPPORT_STATUSES]}</span></header><div className={s.thread}>{selected.messages.map(m=><article key={m.id} data-team={m.authorRole==="ADMIN"}><div><strong>{m.authorRole==="ADMIN"?"LinkWe support":selected.storeName}</strong><time>{new Date(m.createdAt).toLocaleString("en-TT",{timeZone:"America/Port_of_Spain"})}</time></div><p>{m.body}</p></article>)}</div><form key={selected.id} action={data=>start(async()=>{setError("");const result=await updateSupportTicket(selected.id,data);if(result.error)setError(result.error);else router.refresh();})}><label>Your reply<textarea name="body" maxLength={5000} rows={4} placeholder="Add an update or more details…"/></label><div className={s.replyFooter}><select name="status" aria-label="Ticket status"><option value="">{admin?"Send and request vendor reply":"Send and reopen"}</option>{Object.entries(SUPPORT_STATUSES).filter(([key])=>admin||["OPEN","RESOLVED"].includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className={s.primary} disabled={pending}>{pending?"Saving…":"Send update"}<Send size={16}/></button></div></form></>:<div className={s.welcome}><CheckCircle2 size={48}/><h2>Support, without the guesswork.</h2><p>Choose a ticket to see its status, read replies and add an update. Resolved tickets stay in your history and can be reopened.</p><Link href="/faq">Visit the help centre →</Link></div>}</section></div>}
 {error&&<p role="alert" className={s.error}>{error}</p>}<p className={s.note}>Messages are private to your business and LinkWe administrators. This is a support queue; replies are not instant.</p></main>;
}
