ALTER TYPE "SplitOrderStatus" ADD VALUE IF NOT EXISTS 'PREPARING';
ALTER TYPE "SplitOrderStatus" ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE "SplitOrderStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_LINKWE';
ALTER TYPE "SplitOrderStatus" ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
