"use client";
import { useId, useState } from "react";
import { Check, ChevronDown, Search, X } from "lucide-react";
import {swatchPaint} from "@/lib/variant-options";
import s from "./filters.module.css";
export type FilterOption={value:string;label:string};
export function FilterSelect({label,value,options,onChange,placeholder="Any",id}:{label:string;value:string;options:FilterOption[];onChange:(value:string)=>void;placeholder?:string;id?:string}){
 const uid=useId(),[q,setQ]=useState("");const fieldId=id??uid;const filtered=options.filter(option=>option.label.toLowerCase().includes(q.trim().toLowerCase()));
 return <div className={s.field}><label htmlFor={fieldId}>{label}{value&&<span className={s.selectedDot}/>}</label>{options.length>12&&<div className={s.find}><Search size={14}/><input type="search" value={q} onChange={e=>setQ(e.target.value)} aria-label={`Find ${label.toLowerCase()} options`} placeholder={`Find ${label.toLowerCase()}…`}/>{q&&<button type="button" onClick={()=>setQ("")} aria-label={`Clear ${label.toLowerCase()} search`}><X size={13}/></button>}</div>}<div className={s.select}><select id={fieldId} value={value} onChange={e=>onChange(e.target.value)}><option value="">{placeholder}</option>{value&&!filtered.some(option=>option.value===value)&&<option value={value}>{options.find(option=>option.value===value)?.label??value.replaceAll("_"," ")}</option>}{filtered.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown size={15}/></div>{q&&<small aria-live="polite">{filtered.length} matching options</small>}</div>;
}
export function FilterChoices({label,value,options,onChange}:{label:string;value:string;options:FilterOption[];onChange:(value:string)=>void}){return <fieldset className={s.field}><legend>{label}</legend><div className={s.choices}>{options.map(option=><button type="button" key={option.value} aria-pressed={value===option.value} onClick={()=>onChange(value===option.value?"":option.value)}>{value===option.value&&<Check size={12}/>} {option.label}</button>)}</div></fieldset>;}
export function ColourSwatches({value,options,onChange}:{value:string;options:{value:string;hex:string}[];onChange:(value:string)=>void}){return <fieldset className={s.field}><legend>Colour <small>{value||"Any shade"}</small></legend><div className={s.swatches}>{options.map(option=><button type="button" key={option.value} title={option.value} aria-label={`Filter by ${option.value}`} aria-pressed={value.toLowerCase()===option.value.toLowerCase()} onClick={()=>onChange(value===option.value?"":option.value)}><span style={{background:swatchPaint(option.value,option.hex)}}>{value.toLowerCase()===option.value.toLowerCase()&&<Check size={14}/>}</span><small>{option.value}</small></button>)}</div></fieldset>;}
