"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { getSession } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { dayRangeTrinidad } from "@/lib/timezone/trinidad";
import { loadCheckoutCart } from "@/lib/checkout/compute-cart-shipping";
import { CouponError, normalizeCoupon, originalCouponSubtotal, type CouponSnapshot } from "@/lib/coupons/pricing";
import { priceCoupon } from "@/lib/coupons/server";
export type StoreCouponRow={id:string;code:string;discountType:string;discountValue:number;minimumMinor:number;scopes:string[];active:boolean;targets:string[];expiresAt:string|null};
export type SaveCouponInput={id?:string;code:string;discountType:string;discountValue:number;minimumMinor:number;scopes:string[];expiresAt:string|null;targetMode?:"all"|"selected";targets?:string[]};
async function ownedStore(){const session=await getSession();if(!session||session.role!=="VENDOR")throw new CouponError("Please sign in as a vendor.");const store=await prisma.store.findUnique({where:{ownerId:session.userId},select:{id:true}});if(!store)throw new CouponError("Create your store first.");return store;}
export async function listStoreCoupons():Promise<{ok:true;coupons:StoreCouponRow[]}|{ok:false;error:string}>{try{const store=await ownedStore();const rows=await prisma.storeCoupon.findMany({where:{storeId:store.id},orderBy:{createdAt:"desc"}});return{ok:true,coupons:rows.map(row=>({...row,expiresAt:row.expiresAt?.toISOString()??null}))};}catch(e){return{ok:false,error:e instanceof CouponError?e.message:"Could not load coupons."};}}
export async function saveStoreCoupon(input:SaveCouponInput){try{const store=await ownedStore();const code=normalizeCoupon(input.code??"");if(!/^[A-Z0-9][A-Z0-9_-]{2,29}$/.test(code))throw new CouponError("Use 3–30 letters, numbers, hyphens or underscores for your code.");if(!["PERCENT","FIXED"].includes(input.discountType)||!Number.isSafeInteger(input.discountValue)||input.discountValue<=0||input.discountValue>100000000||input.discountType==="PERCENT"&&input.discountValue>100)throw new CouponError("Enter a valid discount; percentages can be 1–100%.");if(!Number.isSafeInteger(input.minimumMinor)||input.minimumMinor<0||input.minimumMinor>100000000)throw new CouponError("Enter a valid minimum spend.");let scopes=[...new Set(input.scopes)];if((input.targetMode!=="selected"&&!scopes.length)||scopes.some(s=>!["product","service","event"].includes(s)))throw new CouponError("Choose at least one creation type.");let expiresAt:Date|null=null;if(input.expiresAt){if(!/^\d{4}-\d{2}-\d{2}$/.test(input.expiresAt)||Number.isNaN(Date.parse(input.expiresAt)))throw new CouponError("Choose a valid expiry date.");expiresAt=dayRangeTrinidad(input.expiresAt).end;if(expiresAt<=new Date())throw new CouponError("Choose an expiry date in the future.");}
 const targets=input.targetMode==="selected"?[...new Set(input.targets??[])]:[];
 if(input.targetMode!==undefined&&!["all","selected"].includes(input.targetMode))throw new CouponError("Choose valid coupon coverage.");
 if(input.targetMode==="selected"){
   if(!targets.length||targets.length>500||targets.some(key=>typeof key!=="string"||! /^(product|service|event|ticket):[A-Za-z0-9_-]+$/.test(key)))throw new CouponError("Choose between 1 and 500 creations for this coupon.");
   const products=await prisma.product.findMany({where:{storeId:store.id,id:{in:targets.filter(key=>key.startsWith("product:")||key.startsWith("service:")).map(key=>key.split(":")[1])}},select:{id:true,isService:true}});
   const events=await prisma.event.findMany({where:{storeId:store.id,id:{in:targets.filter(key=>key.startsWith("event:")).map(key=>key.split(":")[1])}},select:{id:true}});
   const tickets=await prisma.eventTicketType.findMany({where:{event:{storeId:store.id},id:{in:targets.filter(key=>key.startsWith("ticket:")).map(key=>key.split(":")[1])}},select:{id:true}});
   const allowed=new Set([...products.map(row=>`${row.isService?"service":"product"}:${row.id}`),...events.map(row=>`event:${row.id}`),...tickets.map(row=>`ticket:${row.id}`)]);
   if(targets.some(key=>!allowed.has(key)))throw new CouponError("Choose creations that belong to your store.");
   scopes=[...new Set(targets.map(key=>key.startsWith("product:")?"product":key.startsWith("service:")?"service":"event"))];
 }
 const data={code,discountType:input.discountType,discountValue:input.discountValue,minimumMinor:input.minimumMinor,scopes,expiresAt,targets};if(input.id){const updated=await prisma.storeCoupon.updateMany({where:{id:input.id,storeId:store.id},data});if(!updated.count)throw new CouponError("Coupon not found.");}else await prisma.storeCoupon.create({data:{...data,storeId:store.id}});revalidatePath("/dashboard/vendor/creation","layout");return{ok:true as const};
 }catch(e){return{ok:false as const,error:e instanceof CouponError?e.message:e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002"?"You already have a coupon with this code.":"Could not save this coupon."};}}
export async function toggleStoreCoupon(id:string,active:boolean){try{const store=await ownedStore();if(typeof active!=="boolean")throw new CouponError("Invalid coupon status.");const changed=await prisma.storeCoupon.updateMany({where:{id,storeId:store.id},data:{active}});if(!changed.count)throw new CouponError("Coupon not found.");revalidatePath("/dashboard/vendor/creation","layout");return{ok:true as const};}catch(e){return{ok:false as const,error:e instanceof CouponError?e.message:"Could not update the coupon."};}}
export async function previewStoreCoupon(input:{kind:"cart"|"service"|"request";id?:string;code:string}):Promise<{ok:true;code:string;discountMinor:number;totalMinor:number}|{ok:false;error:string}>{
 try{const session=await getSession();if(!session)throw new CouponError("Sign in to apply a coupon.");if(!input.code?.trim())throw new CouponError("Enter your coupon code.");let snapshots:CouponSnapshot[]=[];let subtotal=0;
 if(input.kind==="cart"){const cart=await loadCheckoutCart(session.userId);const grouped=new Map<string,number>();for(const item of cart){if(item.product.isService)continue;grouped.set(item.product.storeId,(grouped.get(item.product.storeId)??0)+Math.round((item.variant?.price??item.product.price)*100)*item.quantity);}subtotal=[...grouped.values()].reduce((a,b)=>a+b,0);for(const [storeId]of grouped){try{const quote=await priceCoupon(storeId,"product",input.code,cart.filter(item=>item.product.storeId===storeId&&!item.product.isService).map(item=>({key:`product:${item.productId}`,subtotalMinor:Math.round((item.variant?.price??item.product.price)*100)*item.quantity})));if(quote)snapshots.push(quote);}catch(e){if(!(e instanceof CouponError))throw e;}}if(!snapshots.length)throw new CouponError("This code is not eligible for the products in your cart. Check the code and its minimum spend.");}
 else if(input.kind==="request"){const request=await prisma.onDemandRequest.findFirst({where:{id:input.id??"",customerId:session.userId,status:"ACCEPTED"},select:{storeId:true,serviceId:true,quotedPrice:true,couponSnapshot:true}});if(!request||request.quotedPrice==null)throw new CouponError("This quote is not ready for payment.");subtotal=originalCouponSubtotal(request.couponSnapshot,Math.round(request.quotedPrice*100));const quote=await priceCoupon(request.storeId,"service",input.code,[{key:`service:${request.serviceId}`,subtotalMinor:subtotal}]);if(quote)snapshots=[quote];}
 else if(input.kind==="service"){const service=await prisma.product.findFirst({where:{id:input.id??"",isService:true,isPublished:true,isArchived:false},select:{id:true,storeId:true,price:true,serviceType:true,subscriptionTrialPeriod:true,subscriptionTrialPrice:true}});if(!service)throw new CouponError("Service not found.");subtotal=Math.round(service.price*100);if(service.serviceType==="SUBSCRIPTION"&&service.subscriptionTrialPeriod){const previous=await prisma.customerServiceSubscription.findFirst({where:{productId:service.id,customerId:session.userId},select:{id:true}});if(!previous)subtotal=Math.round((service.subscriptionTrialPrice??0)*100);}const quote=await priceCoupon(service.storeId,"service",input.code,[{key:`service:${service.id}`,subtotalMinor:subtotal}]);if(quote)snapshots=[quote];}
 else throw new CouponError("Invalid coupon request.");
 const discountMinor=snapshots.reduce((sum,row)=>sum+row.discountMinor,0);return{ok:true,code:normalizeCoupon(input.code),discountMinor,totalMinor:subtotal-discountMinor};
 }catch(e){return{ok:false,error:e instanceof CouponError?e.message:"Could not check that coupon. Please try again."};}
}
