"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, CheckCircle2, CircleHelp, Link2, RefreshCw, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { getAdminAnalytics } from "@/app/actions/admin-analytics";
import { useStudioRex } from "@/components/admin/rex/StudioRexProvider";
import { objectParameters } from "@/lib/admin/studio-rex";
import { campaignUrl, DEFAULT_FILTERS, parseFilters, percentChange, type AnalyticsFilters } from "@/lib/analytics/model";
import { analyticsCsv } from "@/lib/analytics/export";
import type { AnalyticsReport, Metric, Row } from "@/lib/analytics/report";
import s from "./analytics.module.css";

const SECTIONS = [{ id:"overview",label:"At a glance" },{ id:"journey",label:"Customer journey" },{ id:"audience",label:"People & discovery" },{ id:"vendors",label:"Vendor progress" },{ id:"operations",label:"Business activity" },{ id:"campaigns",label:"Marketing" },{ id:"health",label:"Data & definitions" }] as const;
type Section = typeof SECTIONS[number]['id'];
const money = (minor: number) => `TTD ${(minor / 100).toLocaleString("en-TT", {maximumFractionDigits:2})}`;
const date = (value: string) => new Date(value).toLocaleDateString("en-TT",{day:"numeric",month:"short",year:"numeric",timeZone:"America/Port_of_Spain"});
function display(metric: Metric) { return metric.value === null ? "Unavailable" : metric.unit === "money" ? money(metric.value) : metric.unit === "percent" ? `${metric.value.toFixed(1)}%` : metric.value.toLocaleString(); }
function download(content: string, filename: string, type = "text/csv;charset=utf-8") { const url=URL.createObjectURL(new Blob([content],{type})); const link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }

function Rows({title,subtitle,rows,empty="No matching activity in this period.",moneyValues=false}: {title:string;subtitle:string;rows:Row[];empty?:string;moneyValues?:boolean}) {
  return <section className={s.panel}><div className={s.panelHead}><div><h2>{title}</h2><p>{subtitle}</p></div><BarChart3 size={19}/></div>{rows.length?<div className={s.rows}>{rows.map((row,i)=><div className={s.row} key={`${row.label}-${i}`}><div><strong>{row.label.replaceAll('_',' ')}</strong>{row.detail&&<p>{row.detail}</p>}</div><div><b>{row.count.toLocaleString()}</b>{moneyValues&&row.value!==undefined&&<small>{money(row.value)}</small>}</div></div>)}</div>:<div className={s.empty}><Activity size={24}/><p>{empty}</p></div>}</section>;
}
export default function AnalyticsWorkspace() {
  const [report,setReport]=useState<AnalyticsReport|null>(null),[filters,setFilters]=useState<AnalyticsFilters>(DEFAULT_FILTERS),[section,setSection]=useState<Section>('overview'),[definitions,setDefinitions]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [comparisons,setComparisons]=useState<Array<Pick<AnalyticsReport,'filters'|'metrics'|'funnel'|'generatedAt'|'health'>>>([]);
  const [campaign,setCampaign]=useState({path:'/shop',source:'instagram',medium:'social',campaign:''}),[link,setLink]=useState('');
  const latest=useRef<AnalyticsReport|null>(null),request=useRef(0),currentFilters=useRef(filters),busyRef=useRef(false);
  const refresh=useCallback(async(next:AnalyticsFilters=currentFilters.current)=>{
    const serial=++request.current;busyRef.current=true;setLoading(true);setError('');
    try {const data=await getAdminAnalytics(next);if(serial===request.current){if(latest.current && JSON.stringify(latest.current.filters)!==JSON.stringify(next)){const old=latest.current;setComparisons(items=>[...items.filter(item=>JSON.stringify(item.filters)!==JSON.stringify(old.filters)),{filters:old.filters,metrics:old.metrics,funnel:old.funnel,generatedAt:old.generatedAt,health:old.health}].slice(-3));}latest.current=data;currentFilters.current=next;setReport(data);setFilters(next);}return data;}
    catch(e){if(serial===request.current)setError(e instanceof Error?e.message:'The report could not load. Please try again.');throw e;}
    finally{if(serial===request.current){busyRef.current=false;setLoading(false);}}
  },[]);
  useEffect(()=>{void refresh().catch(()=>{});},[refresh]);
  const updateFilters=async(value:unknown)=>refresh(parseFilters(value));
  function exportReport(){if(!latest.current)throw new Error('Load a report before exporting.');download(analyticsCsv(latest.current),`linkwe-analytics-${latest.current.start.slice(0,10)}.csv`);setNotice('Your report download is ready.');}
  function buildLink(value=campaign){const result=campaignUrl(window.location.origin,value);setCampaign(value);setLink(result);setNotice('Campaign link created. Copy it from the field or download it.');return result;}
  function downloadLink(){if(!link)throw new Error('Create a campaign link first.');download(link,'linkwe-campaign-link.txt','text/plain');setNotice('Your campaign link download is ready.');}
  const rexWorking=useStudioRex({key:'analytics',title:'LinkWe analytics',busy:loading,state:{filters,section,definitions,comparisons,campaign,generatedLink:link,report,error,loading,capabilities:'Every page control has a matching action. Business totals use date range only; traffic filters never alter money totals.'},actions:[
    {name:'analytics_filter',description:'Change date range (1=today,7,30,90), visitor device and visitor source, then load the report. Money and operational totals use the date range only. Queue this alone before assessing new data.',parameters:objectParameters({days:{type:'number',enum:[1,7,30,90]},device:{type:'string',enum:['all','mobile','desktop','tablet']},source:{type:'string'}},[])},
    {name:'analytics_section',description:'Show a report section using the same tabs as the administrator.',parameters:objectParameters({section:{type:'string',enum:SECTIONS.map(x=>x.id)}},['section'])},
    {name:'analytics_refresh',description:'Refresh all data for the current filters. Queue alone before assessment.',parameters:objectParameters()},
    {name:'analytics_reset',description:'Reset to last 30 days, all devices and all sources, then reload.',parameters:objectParameters()},
    {name:'analytics_export',description:'Download the complete currently loaded report as CSV, including definitions, coverage, comparisons and every report table.',parameters:objectParameters()},
    {name:'analytics_definitions',description:'Show or hide explanations under the main metric cards.',parameters:objectParameters({show:{type:'boolean'}},['show'])},
    {name:'analytics_campaign',description:'Create a campaign link. Requires a public relative LinkWe path, source, medium and campaign name. This prepares a link only; it does not publish an ad or spend money.',parameters:objectParameters({path:{type:'string'},source:{type:'string'},medium:{type:'string'},campaign:{type:'string'}},['path','source','medium','campaign'])},
    {name:'analytics_download_link',description:'Download the already generated campaign link as a text file.',parameters:objectParameters()},
  ],run:async step=>{
    if(busyRef.current)throw new Error('Wait for the report to finish loading.');
    switch(step.action){
      case 'analytics_filter':{const allowed=['days','device','source'];if(Object.keys(step.args).some(k=>!allowed.includes(k)))throw new Error('Unknown filter.');await updateFilters({...currentFilters.current,...step.args});return{message:'Applied the filters and loaded the matching report. Read the updated report before drawing conclusions.'};}
      case 'analytics_refresh':await refresh();return{message:'Refreshed the current analytics report.'};
      case 'analytics_reset':await updateFilters(DEFAULT_FILTERS);return{message:'Reset to the last 30 days, all devices and all traffic sources.'};
      case 'analytics_section':if(!SECTIONS.some(x=>x.id===step.args.section))throw new Error('Choose an available report section.');setSection(step.args.section as Section);return{message:`Opened ${SECTIONS.find(x=>x.id===step.args.section)!.label}.`};
      case 'analytics_export':exportReport();return{message:'Prepared the current report download, including its limitations and definitions.'};
      case 'analytics_definitions':if(typeof step.args.show!=='boolean')throw new Error('Choose whether to show explanations.');setDefinitions(step.args.show);return{message:step.args.show?'Showing metric explanations.':'Hid metric explanations.'};
      case 'analytics_campaign':{const values={path:String(step.args.path??''),source:String(step.args.source??''),medium:String(step.args.medium??''),campaign:String(step.args.campaign??'')};const result=buildLink(values);setSection('campaigns');return{message:`Created campaign link: ${result}`};}
      case 'analytics_download_link':downloadLink();return{message:'Prepared the campaign link download.'};
      default:throw new Error('That analytics action is unavailable.');
    }
  }});
  const disabled=loading||rexWorking;
  const loaded=!!report;
  const metric=(key:string)=>report?.metrics.find(m=>m.key===key);
  const trafficEmpty=!report?.health.trafficAvailable?'Visitor data is unavailable. Business records are still shown.':!report.health.firstEvent?'Not tracked yet. Consented activity will appear after collection starts.':'No measured activity matches this period and these filters.';
  function cards(keys:string[]){return <div className={s.cards}>{keys.map(key=>{const m=metric(key);if(!m)return null;const isTraffic=['visitors','views','enquiries','sessions','newVisitors','returningVisitors'].includes(key);const unknown=isTraffic&&report?.health.trafficAvailable&&!report?.health.firstEvent;const change=m.value!==null&&m.previous!==null&&!(isTraffic&&report?.health.partialPeriod)?percentChange(m.value,m.previous):null;return <article className={s.card} key={key}><span>{m.label}</span><strong>{unknown?'Not tracked yet':display(m)}</strong><small>{change!==null?`${change>0?'+':''}${change.toFixed(1)}% vs previous period`:isTraffic&&report?.health.partialPeriod?'History still building':m.previous===0?'No previous baseline':'See definition for scope'}</small>{definitions&&<p>{m.definition}</p>}</article>;})}</div>;}
  return <div className={s.workspace}>
    <header className={s.hero}><div><span className={s.eyebrow}><Activity size={14}/> LINKWE ANALYTICS</span><h1>Your marketplace.<br/><em>A clearer picture.</em></h1><p>Understand what’s happening, find what needs attention, and decide what to do next.</p></div><div className={s.heroBadge}><Sparkles size={23}/><strong>Make sense of it<br/>with Rex.</strong><span>Ask a question. Explore a pattern.<br/>Take the next step together.</span></div></header>
    <div className={s.toolbar}><label>Time period<select value={filters.days} disabled={disabled} onChange={e=>void updateFilters({...filters,days:Number(e.target.value)}).catch(()=>{})}><option value={1}>Today</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><label>Visitor device<select value={filters.device} disabled={disabled} onChange={e=>void updateFilters({...filters,device:e.target.value}).catch(()=>{})}>{['all','mobile','desktop','tablet'].map(x=><option key={x} value={x}>{x==='all'?'All devices':x}</option>)}</select></label><label>Visitor source<select value={filters.source} disabled={disabled} onChange={e=>void updateFilters({...filters,source:e.target.value}).catch(()=>{})}>{[...new Set(['all',filters.source,...(report?.sources.map(r=>r.label)??[])])].map(x=><option key={x} value={x}>{x==='all'?'All sources':x}</option>)}</select></label><div className={s.tools}><button disabled={disabled} onClick={()=>void refresh().catch(()=>{})} aria-label="Refresh analytics"><RefreshCw size={17} className={loading?s.spin:undefined}/></button><button disabled={disabled} onClick={()=>void updateFilters(DEFAULT_FILTERS).catch(()=>{})}>Reset</button><button disabled={!loaded||disabled} onClick={exportReport}><ArrowDownToLine size={15}/> Export</button></div></div>
    <div className={s.context}><span>{report?report.periodLabel:'Preparing your report…'}</span><button onClick={()=>setDefinitions(!definitions)} disabled={rexWorking}><CircleHelp size={14}/>{definitions?'Hide explanations':'Explain the numbers'}</button></div>
    <p className={s.scope}>Device and source refine visitor reports. Money and business activity always use the selected date range across all eligible accounts.</p>
    {error&&<div role="alert" className={s.alert}>{error}{report?' Your last loaded report is still shown.':''}<button onClick={()=>void refresh().catch(()=>{})} disabled={disabled}>Try again</button></div>}
    {notice&&<p role="status" className={s.notice}>{notice}</p>}
    <nav className={s.tabs} aria-label="Analytics reports">{SECTIONS.map(item=><button key={item.id} onClick={()=>setSection(item.id)} aria-current={section===item.id?'page':undefined} disabled={rexWorking}>{item.label}</button>)}</nav>
    {loading&&!report?<div className={s.loading} role="status"><RefreshCw size={24} className={s.spin}/><p>Bringing your marketplace into view…</p></div>:report&&<div aria-busy={loading} className={s.body}>
      {section==='overview'&&<>
        {cards(['collected','payments','visitors','enquiries'])}
        <section className={s.panel}><div className={s.panelHead}><div><span className={s.eyebrow}>YOUR NEXT GOOD MOVE</span><h2>What needs your attention</h2><p>Evidence to investigate, with a practical next step.</p></div><Sparkles size={21}/></div><div className={s.insights}>{report.insights.map((item,i)=><button key={item.title} onClick={()=>setSection(item.section as Section)} disabled={rexWorking}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><ArrowUpRight size={18}/></button>)}</div></section>
        <section className={s.panel}><div className={s.panelHead}><div><h2>Payments through the period</h2><p>Confirmed live payments · before refunds · TTD</p></div><TrendingUp size={20}/></div>{report.daily.length?<div className={s.chart} role="img" aria-label="Daily confirmed payments. Values are listed below.">{report.daily.map(day=><div key={day.label} title={`${day.label}: ${money(day.value??0)}`}><span style={{height:`${Math.max(2,(day.value??0)/Math.max(...report.daily.map(r=>r.value??0),1)*100)}%`}}/><small>{day.label.slice(5)}</small></div>)}</div>:<p className={s.empty}>No confirmed live payments in this period.</p>}</section>
        {cards(['vendor','commission','platform','refunded'])}
      </>}
      {section==='journey'&&<>
        <section className={s.panel}><div className={s.panelHead}><div><h2>From interest to a purchase</h2><p>Consented sessions completing these steps in order during the selected period. Product shopping only; bookings and tickets are reported separately.</p></div><ArrowRight size={20}/></div>{!report.health.firstEvent||!report.health.trafficAvailable?<p className={s.empty}>{trafficEmpty}</p>:<div className={s.funnel}>{report.funnel.map((row,i)=>{const previous=report.funnel[i-1]?.count;return <div key={row.label}><div><span>{i+1}</span><strong>{row.label}</strong><b>{row.count}</b></div><div className={s.track}><span style={{width:`${report.funnel[0]?.count?row.count/report.funnel[0].count*100:0}%`}}/></div><small>{i>0&&previous?`${(row.count/previous*100).toFixed(1)}% of the preceding step continued`:'Starting point for this journey'}</small></div>;})}</div>}</section>
        {cards(['failed','payments','refunded'])}<Rows title="Checkout obstacles" subtitle="Categorised errors only; personal form entries are never included." rows={report.errors} empty={trafficEmpty}/><Rows title="Ways people reach out" subtitle="A click signals interest. It does not confirm a call, message or sale." rows={report.contacts} empty={trafficEmpty}/>
      </>}
      {section==='audience'&&<>{cards(['visitors','sessions','newVisitors','returningVisitors','repeat','buyers'])}<Rows title="Popular pages" subtitle="Measured page views. Public paths only." rows={report.popular} empty={trafficEmpty}/><Rows title="Searches with no results" subtitle="Short search terms are screened for personal information. Counts can include searches narrowed by filters." rows={report.searches} empty={trafficEmpty}/><Rows title="Where visits begin" subtitle="Session landing source. Attributed payment amounts are shown separately from visit counts." rows={report.sources} empty={trafficEmpty} moneyValues/></>}
      {section==='vendors'&&<Rows title="From joining to doing business" subtitle="A cohort of accounts and stores created in the selected period, viewed at their current stage. These are milestones, not a sequential conversion funnel." rows={report.vendors}/>}
      {section==='operations'&&<>{cards(['collected','vendor','commission','platform','refundDeductions'])}<Rows title="Business activity" subtitle="Each measure uses the date described below it. Older records may lack test markers." rows={report.operations}/><Rows title="What the payments were for" subtitle="Confirmed live payment counts and collected TTD amounts, before refunds." rows={report.paymentTypes} moneyValues/><Rows title="Daily payment amounts" subtitle="Dates in Trinidad and Tobago time. Counts are successful payment transactions." rows={report.daily} moneyValues/></>}
      {section==='campaigns'&&<><Rows title="How your campaigns are doing" subtitle="Measured visits, contact clicks and linked confirmed payments. Attribution follows the checkout session’s landing source; advertising spend is not connected." rows={report.campaigns} empty={trafficEmpty} moneyValues/><section className={s.panel}><div className={s.panelHead}><div><h2>Make a link you can measure</h2><p>Use a separate campaign name for each promotion. Rex can prepare these links too.</p></div><Link2 size={21}/></div><form className={s.linkForm} onSubmit={e=>{e.preventDefault();try{buildLink();}catch(e){setNotice(e instanceof Error?e.message:'Check the link details.');}}}>{([{key:'path',label:'LinkWe page',placeholder:'/shop'},{key:'source',label:'Where you will share it',placeholder:'instagram'},{key:'medium',label:'Type of promotion',placeholder:'social'},{key:'campaign',label:'Campaign name',placeholder:'christmas-market'}] as const).map(field=><label key={field.key}>{field.label}<input required value={campaign[field.key]} placeholder={field.placeholder} disabled={rexWorking} onChange={e=>{setCampaign({...campaign,[field.key]:e.target.value});setLink('');}}/></label>)}<button type="submit" disabled={rexWorking}><Link2 size={16}/> Create campaign link</button></form>{link&&<div className={s.generated}><label>Your campaign link<input readOnly aria-label="Generated campaign link" value={link} onFocus={e=>e.target.select()}/></label><button onClick={downloadLink} disabled={rexWorking}><ArrowDownToLine size={15}/> Download link</button></div>}</section></>}
      {section==='health'&&<><section className={s.panel}><div className={s.panelHead}><div><h2>Know what the numbers can tell you</h2><p>Rex receives these same definitions and limitations with your report.</p></div><ShieldCheck size={21}/></div><div className={s.health}><p><CheckCircle2 size={17}/><span><strong>Business records</strong>Payment and operational records queried at {new Date(report.generatedAt).toLocaleTimeString('en-TT',{timeZone:'America/Port_of_Spain',hour:'numeric',minute:'2-digit'})}.</span></p><p><Activity size={17}/><span><strong>Visitor tracking</strong>{!report.health.trafficAvailable?'Unavailable — check database migration and collection.':report.health.firstEvent?`Started ${date(report.health.firstEvent)}. Last event ${report.health.lastEvent?date(report.health.lastEvent):'not available'}.`:'Not tracked yet. Activity starts after deployment and visitor consent.'}</span></p><p><CircleHelp size={17}/><span><strong>{report.health.legacyPayments} unclassified legacy payments</strong>Excluded from payment totals until their live/sandbox environment can be verified.</span></p><p><Sparkles size={17}/><span><strong>Rex {report.health.rexConfigured?'is connected':'needs a connection'}</strong>{report.health.rexConfigured?'Ask him to assess, compare, filter or export.':'The page works manually. Configure the existing Rex connection to enable conversation.'}</span></p></div><ul className={s.notes}>{report.health.notes.map(note=><li key={note}>{note}</li>)}</ul></section><section className={s.panel}><h2>Every number, explained</h2><dl className={s.definitions}>{report.metrics.map(m=><div key={m.key}><dt>{m.label}</dt><dd>{m.definition}</dd></div>)}</dl></section><Rows title="Page performance samples" subtitle="Average LCP and INP in milliseconds; CLS is a layout-shift score. Counts are measured samples. Compare like-for-like device filters." rows={report.performance.map(r=>({...r,detail:`Average: ${(r.value??0).toFixed(r.label==='CLS'?3:0)}${r.label==='CLS'?'':' ms'}`}))} empty={trafficEmpty}/></>}
    </div>}
  </div>;
}
