import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth/session";
import { CreateService, ServiceActions } from "./service-controls";
export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  if ((await getSession())?.role !== "ADMIN") redirect("/login");
  const { q = "", page: pageRaw = "1" } = await searchParams;
  const page = Math.max(1,parseInt(pageRaw) || 1);
  const where = { isService: true, ...(q ? { name: { contains: q.slice(0,200), mode: "insensitive" as const } } : {}) };
  const [rows,total,stores] = await Promise.all([prisma.product.findMany({ where, take: 24, skip: (page-1)*24, orderBy: { createdAt: "desc" }, select: { id: true, name: true, price: true, serviceType: true, isPublished: true, isArchived: true, store: { select: { name: true } }, _count: { select: { bookings: true, onDemandRequests: true, customerServiceSubscriptions: true } } } }), prisma.product.count({ where }), prisma.store.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } })]);
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><div><h1 className="text-3xl font-semibold">Services</h1><p className="mt-2 text-sm text-zinc-500">Manage service pricing, availability, booking rules and publication across all stores.</p></div><CreateService stores={stores}/><form className="flex gap-2"><input name="q" defaultValue={q} aria-label="Search services" placeholder="Search services…" className="min-h-11 min-w-0 flex-1 rounded-xl border px-4"/><button className="rounded-xl bg-zinc-900 px-5 text-white">Search</button></form><p className="text-sm text-zinc-500">{total} services · Page {page}</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(row => <article className="rounded-2xl border bg-white p-5" key={row.id}><p className="text-xs text-zinc-500">{row.store.name} · {row.serviceType?.replaceAll("_"," ")}</p><h2 className="mt-2 text-lg font-semibold">{row.name}</h2><p className="mt-2 text-orange-700">TTD {row.price.toFixed(2)}</p><p className="my-3 text-xs text-zinc-500">{row.isArchived ? "Archived" : row.isPublished ? "Published" : "Draft"} · {row._count.bookings} bookings · {row._count.onDemandRequests} requests · {row._count.customerServiceSubscriptions} subscriptions</p><Link href={`/dashboard/admin/records/service/${row.id}`} className="mb-3 inline-flex min-h-10 items-center rounded-xl bg-zinc-900 px-4 text-sm text-white">Edit service</Link><ServiceActions id={row.id} name={row.name} archived={row.isArchived}/></article>)}</div>{!rows.length && <p className="rounded-xl border p-6 text-zinc-500">No services match this search.</p>}<div className="flex gap-4">{page>1 && <Link href={`?q=${encodeURIComponent(q)}&page=${page-1}`}>← Previous</Link>}{page*24<total && <Link href={`?q=${encodeURIComponent(q)}&page=${page+1}`}>Next →</Link>}</div></main>;
}
