"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight, CalendarDays, Clock3, Search, ShoppingBag, Sparkles, Store, X } from "lucide-react";
import { getPopularSearches } from "@/app/actions/search";
import SearchDropdown from "@/components/search/SearchDropdown";
import { useSearch } from "@/lib/hooks/use-search";
import s from "./main-search.module.css";
const KEY="linkwe:recent-searches:v2";
export default function NavSearchInput({variant,inputId="public-nav-search",onCloseOverlay,light=false}:{variant:"desktop"|"mobile-overlay";inputId?:string;onCloseOverlay?:()=>void;light?:boolean}){
 const router=useRouter();const root=useRef<HTMLDivElement>(null);const input=useRef<HTMLInputElement>(null);const [query,setQuery]=useState("");const [open,setOpen]=useState(variant==="mobile-overlay");const [recent,setRecent]=useState<string[]>([]);const [popular,setPopular]=useState<string[]>([]);
 const [kind,setKind]=useState("all");
 const {results,isLoading,error,detectedRegion}=useSearch(query,{preview:true,enabled:open,type:kind});
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(KEY)??"[]");if(Array.isArray(saved))setRecent(saved.filter(x=>typeof x==="string").slice(0,6));}catch{}void getPopularSearches().then(setPopular).catch(()=>{});},[]);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[]);
 const close=()=>{setOpen(false);onCloseOverlay?.();};
 function save(q:string){const next=[q,...recent.filter(r=>r.toLowerCase()!==q.toLowerCase())].slice(0,6);setRecent(next);try{sessionStorage.setItem(KEY,JSON.stringify(next));}catch{}}
 function go(q:string){const value=q.trim().slice(0,120);if(value.length<2)return;save(value);close();router.push(`/search?q=${encodeURIComponent(value)}${kind!=="all"?`&type=${kind}`:""}`);}
 function keys(e:React.KeyboardEvent){if(e.key==="Escape"){e.preventDefault();close();input.current?.focus();}if(e.key==="ArrowDown"||e.key==="ArrowUp"){const options=Array.from(root.current?.querySelectorAll<HTMLElement>(`[data-search-panel] a, [data-search-panel] button`)??[]);if(!options.length)return;e.preventDefault();const index=options.indexOf(document.activeElement as HTMLElement);const next=index<0?(e.key==="ArrowDown"?0:options.length-1):(index+(e.key==="ArrowDown"?1:-1)+options.length)%options.length;options[next]?.focus();}}
 return <div ref={root} onKeyDown={keys} className={`${s.root} ${light?s.light:""} ${variant==="mobile-overlay"?s.mobile:""}`}><form onSubmit={e=>{e.preventDefault();go(query);}} className={s.field}><Search size={18}/><label htmlFor={inputId} className="sr-only">Search LinkWe</label><input ref={input} id={inputId} type="search" autoFocus={variant==="mobile-overlay"} value={query} maxLength={120} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);}} placeholder="Find your next local favourite…" autoComplete="off" aria-expanded={open} aria-controls={`${inputId}-results`}/>{query&&<button type="button" aria-label="Clear search" onClick={()=>{setQuery("");input.current?.focus();}}><X size={16}/></button>}<button type="submit" aria-label="Search" className={s.go}><ArrowUpRight size={17}/></button></form>
 {open&&<div id={`${inputId}-results`} className={s.panel} data-search-panel>{query.trim().length>=2?<><div className={s.panelHeading}><strong>Discover something local</strong><span>↑ ↓ to explore</span></div><div className={s.scope} aria-label="Search suggestion collections">{[["all","All"],["products","Products"],["services","Services"],["stores","Stores"],["events","Events"]].map(([value,label])=><button type="button" aria-pressed={kind===value} key={value} onClick={()=>setKind(value)}>{label}</button>)}</div><SearchDropdown selectedType={kind} query={query} results={results} isLoading={isLoading} error={error} detectedRegion={detectedRegion} onNavigate={()=>{save(query.trim());close();}}/></>:<><div className={s.panelHeading}><strong>Your next favourite is here.</strong><span>Made for T&amp;T</span></div><div className={s.destinations}>{[["/shop","Shop",ShoppingBag],["/services","Services",Sparkles],["/stores","Stores",Store],["/events","Events",CalendarDays]].map(([href,label,Icon])=>{const Glyph=Icon as typeof Store;return <Link key={String(href)} href={String(href)} onClick={close}><Glyph size={21}/><span>{String(label)}</span><ArrowUpRight size={13}/></Link>;})}</div>{recent.length>0&&<><div className={s.panelHeading}><strong>Recent in this tab</strong><button onClick={()=>{setRecent([]);try{sessionStorage.removeItem(KEY);}catch{}}}>Clear</button></div><div className={s.recent}>{recent.map(q=><button key={q} onClick={()=>go(q)}><Clock3 size={14}/>{q}<ArrowUpRight size={13}/></button>)}</div></>}<p className={s.caption}>A little inspiration</p><div className={s.chips}>{(popular.length?popular.slice(0,6):["Gifts","Beauty","Home","Food","Photography"]).map(q=><button key={q} onClick={()=>go(q)}>{q}</button>)}</div><p className={s.hint}>{query?"Type at least two characters to search.":"Try a product, a service or a town near you."}</p></>}</div>}
 </div>;
}
export function MobileSearchOverlay({open,onClose}:{open:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open){dialog.current?.showModal();dialog.current?.querySelector<HTMLInputElement>("input[type=search]")?.focus();}else dialog.current?.close();},[open]);
 return <dialog ref={dialog} className={s.dialog} aria-label="Search LinkWe" onCancel={onClose}><header><div><small>LINKWE DISCOVER</small><h2>What are you looking for?</h2></div><button onClick={onClose} aria-label="Close search"><X size={22}/></button></header>{open&&<NavSearchInput variant="mobile-overlay" inputId="mobile-search" onCloseOverlay={onClose}/>}</dialog>;
}
