"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { getStaffPortal, manageStaffTimeOff, saveStaffAppointmentNote } from "@/app/actions/staff-access";
import { ymdInTrinidad } from "@/lib/timezone/trinidad";
import { bookingDateLabel } from "@/lib/services/upcoming-bookings";
import s from "@/components/vendor/business-workspace.module.css";
type Member=Awaited<ReturnType<typeof getStaffPortal>>[number];
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
function Membership({member}:{member:Member}){
 const router=useRouter(),[pending,start]=useTransition(),[message,setMessage]=useState("");
 const run=(fn:()=>Promise<unknown>)=>start(async()=>{setMessage("");try{await fn();setMessage("Saved.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}});
 return <section className={s.stack}><div className={s.hero}><p className={s.eyebrow}>YOUR TEAM</p><h2 className={s.heading}>{member.store.name}</h2><p className={s.muted}>{member.name} · {member.bookings.length} upcoming appointments shown, up to 100</p></div>{message&&<p role="status" className={s.muted}>{message}</p>}<div className={s.two}><section className={s.card}><h3 className={s.heading}>Your working hours</h3>{member.availability.filter(d=>d.isActive).map(d=><p className={s.muted} key={d.id} style={{marginTop:10}}>{DAYS[d.dayOfWeek]} · {d.startTime}–{d.endTime}</p>)}{!member.availability.some(d=>d.isActive)&&<p className={s.muted}>Ask your owner to set your working hours.</p>}</section><section className={s.card}><h3 className={s.heading}>Time off</h3><p className={s.muted}>Existing appointments remain assigned. Contact your owner to rearrange them.</p>{member.overrides.map(o=><div className={s.row} key={o.id}><span className={s.muted}>{bookingDateLabel(o.date)} · {o.isBlocked?"Unavailable":"Adjusted hours"}</span>{member.access?.canManageTimeOff&&o.reason==="Team member time off"&&<button disabled={pending} className={s.link} onClick={()=>run(()=>manageStaffTimeOff(member.id,o.date.toISOString().slice(0,10),false))}>Remove</button>}</div>)}{member.access?.canManageTimeOff?<form className={s.toolbar} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>manageStaffTimeOff(member.id,String(f.get("date")),true));}}><input aria-label="Time off date" type="date" name="date" min={ymdInTrinidad()} className={s.input} required/><button className={s.secondary} disabled={pending}>Block date</button></form>:<p className={s.small}>Your owner manages your time off.</p>}</section></div><section className={s.card}><h3 className={s.heading}>Your assigned appointments</h3>{!member.bookings.length&&<p className={s.empty}>You’re all caught up. New assignments appear here.</p>}{member.bookings.map(b=><article className={s.divider} key={b.id+String(b.updatedAt)}><div className={s.row}><div><strong>{b.product.name}</strong><p className={s.muted}>{bookingDateLabel(b.bookingDate)} · {b.startTime}–{b.endTime} · {b.id.slice(-8).toUpperCase()}</p></div><span className={s.badge}>{b.status.toLowerCase().replaceAll("_"," ")}</span></div>{member.access?.canEditNotes?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveStaffAppointmentNote(member.id,b.id,String(f.get("note")),b.updatedAt.toISOString()));}}><label className={s.label}>Shared appointment notes<textarea name="note" className={s.textarea} defaultValue={b.vendorNotes??""} rows={2} maxLength={2000}/></label><button disabled={pending} className={s.secondary}>Save notes</button></form>:<p className={s.muted}>{b.vendorNotes||"No appointment notes."}</p>}</article>)}</section></section>;
}
export default function TeamPortal({members}:{members:Member[]}) {return <div className={s.stack}><div><p className={s.eyebrow}>PEOPLE MAKE IT HAPPEN</p><h1 style={{fontSize:32,fontWeight:650,margin:"8px 0"}}>Your work, in one place.</h1><p className={s.muted}>Your schedule and assigned appointments. All times are in Trinidad & Tobago.</p></div>{members.length?members.map(m=><Membership key={m.id} member={m}/>):<section className={s.card}><h2 className={s.heading}>No active team access yet</h2><p className={s.muted}>Ask your business owner for an invitation link. Use the same email address they invited, verify it, then accept the invitation.</p></section>}</div>;}
