"use client";

import Link from "next/link";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type SavedEvent = { id:string; title:string; slug:string; startDate:string; coverImage:string|null; venueName:string|null; region:string|null; isOnline:boolean };
const KEY = "linkwe:saved-events";
const monthValue = (date:Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;

function EventCard({event}:{event:SavedEvent}) {
  const date=new Date(event.startDate);
  return <Link href={`/events/${event.slug}`} className="group grid min-w-0 grid-cols-[5.5rem_minmax(0,1fr)] gap-3 overflow-hidden rounded-[22px] border border-zinc-200 bg-white p-3 shadow-[0_10px_30px_rgba(28,28,26,.06)] transition duration-300 hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-[0_18px_38px_rgba(128,52,12,.12)] sm:grid-cols-[7rem_minmax(0,1fr)]">
    <div className="relative h-24 overflow-hidden rounded-2xl bg-gradient-to-br from-orange-100 to-zinc-100 sm:h-28">{event.coverImage?<img src={event.coverImage} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<CalendarDays className="absolute left-1/2 top-1/2 size-9 -translate-x-1/2 -translate-y-1/2 text-orange-300"/>}<span className="absolute left-2 top-2 rounded-lg bg-zinc-950/85 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-white backdrop-blur">{date.toLocaleDateString("en-TT",{month:"short",day:"numeric"})}</span></div>
    <div className="flex min-w-0 flex-col justify-center py-1"><span className="text-[9px] font-black uppercase tracking-[.16em] text-[#D4450A]">Saved event</span><h3 className="mt-1 line-clamp-2 text-sm font-black leading-5 text-zinc-950 sm:text-base">{event.title}</h3><p className="mt-2 flex items-center gap-1.5 text-[11px] font-medium text-zinc-500"><Clock3 className="size-3.5 text-orange-500"/>{date.toLocaleDateString("en-TT",{weekday:"short",day:"numeric",month:"short"})} · {date.toLocaleTimeString("en-TT",{hour:"numeric",minute:"2-digit"})}</p><p className="mt-1 flex min-w-0 items-center gap-1.5 truncate text-[11px] text-zinc-500"><MapPin className="size-3.5 shrink-0 text-orange-500"/><span className="truncate">{event.isOnline?"Online event":event.venueName??event.region??"Venue to be announced"}</span></p></div>
  </Link>;
}

export default function EventCollectionsClient(){
  const [events,setEvents]=useState<SavedEvent[]>([]),[loading,setLoading]=useState(true),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [search,setSearch]=useState(""),[region,setRegion]=useState("ALL"),[format,setFormat]=useState("ALL"),[timing,setTiming]=useState("UPCOMING");
  useEffect(()=>{let ids:string[]=[];try{ids=JSON.parse(localStorage.getItem(KEY)??"[]") as string[]}catch{}if(!ids.length){setLoading(false);return}fetch(`/api/events/collection?ids=${encodeURIComponent(ids.join(","))}`).then(r=>r.json()).then(data=>setEvents(data.events??[])).finally(()=>setLoading(false));},[]);
  const regions=useMemo(()=>[...new Set(events.map(e=>e.region).filter((v):v is string=>Boolean(v)))].sort(),[events]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase(),now=Date.now();return events.filter(e=>{const stamp=new Date(e.startDate).getTime();return(!q||`${e.title} ${e.venueName??""} ${e.region??""}`.toLowerCase().includes(q))&&(region==="ALL"||e.region===region)&&(format==="ALL"||(format==="ONLINE"?e.isOnline:!e.isOnline))&&(timing==="ALL"||(timing==="UPCOMING"?stamp>=now:stamp<now));});},[events,format,region,search,timing]);
  const monthEvents=useMemo(()=>filtered.filter(e=>{const d=new Date(e.startDate);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()}),[filtered,month]);
  const firstDay=new Date(month.getFullYear(),month.getMonth(),1).getDay(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),cells=Array.from({length:firstDay+days},(_,i)=>i<firstDay?null:i-firstDay+1),title=month.toLocaleDateString("en-TT",{month:"long",year:"numeric"});
  const nextSaved=filtered.find(e=>new Date(e.startDate).getTime()>=Date.now())??filtered[0];
  const jump=()=>{if(nextSaved){const d=new Date(nextSaved.startDate);setMonth(new Date(d.getFullYear(),d.getMonth(),1));}};
  const chooseMonth=(value:string)=>{const [year,m]=value.split("-").map(Number);if(year&&m)setMonth(new Date(year,m-1,1));};
  if(loading)return <div className="flex min-h-72 flex-col items-center justify-center text-sm text-zinc-500"><span className="flex size-14 animate-pulse items-center justify-center rounded-2xl bg-orange-50"><CalendarDays className="size-7 text-orange-400"/></span><p className="mt-4 font-semibold">Preparing your collection…</p></div>;
  if(!events.length)return <div className="rounded-3xl border border-dashed border-orange-200 bg-white py-20 text-center"><CalendarDays className="mx-auto size-12 text-orange-300"/><h3 className="mt-4 font-black">Your event calendar is ready</h3><p className="mx-auto mt-2 max-w-md text-sm text-zinc-500">Tap the heart on an event to add it here.</p><Link href="/events" className="mt-5 inline-flex rounded-xl bg-[#D4450A] px-5 py-3 text-sm font-bold text-white">Explore events</Link></div>;
  return <div>
    <section className="mb-6 overflow-hidden rounded-[26px] border border-zinc-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-zinc-100 bg-gradient-to-r from-zinc-950 to-[#48200F] px-4 py-4 text-white sm:px-5"><span className="flex size-9 items-center justify-center rounded-xl bg-white/10"><SlidersHorizontal className="size-4 text-orange-300"/></span><div><h2 className="text-sm font-black">Find a saved event</h2><p className="text-[10px] text-white/55">Search, filter or jump directly to a month</p></div></div><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-[minmax(240px,1.4fr)_repeat(3,minmax(130px,.7fr))] lg:p-5"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events or venues…" className="min-h-11 w-full rounded-xl border border-zinc-200 bg-zinc-50 pl-10 pr-3 text-xs outline-none focus:border-[#D4450A] focus:bg-white"/></label><select value={region} onChange={e=>setRegion(e.target.value)} className="min-h-11 rounded-xl border border-zinc-200 bg-zinc-50 px-3 text-xs font-semibold"><option value="ALL">All regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select><select value={format} onChange={e=>setFormat(e.target.value)} className="min-h-11 rounded-xl border border-zinc-200 bg-zinc-50 px-3 text-xs font-semibold"><option value="ALL">All formats</option><option value="IN_PERSON">In person</option><option value="ONLINE">Online</option></select><select value={timing} onChange={e=>setTiming(e.target.value)} className="min-h-11 rounded-xl border border-zinc-200 bg-zinc-50 px-3 text-xs font-semibold"><option value="UPCOMING">Upcoming</option><option value="PAST">Past events</option><option value="ALL">All dates</option></select></div></section>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#D4450A]">Calendar view</p><h2 className="mt-1 text-xl font-black text-zinc-950">{title}</h2><p className="text-xs text-zinc-500">{filtered.length} matching saved event{filtered.length===1?"":"s"}</p></div><div className="flex flex-wrap items-center gap-2"><input type="month" value={monthValue(month)} onChange={e=>chooseMonth(e.target.value)} aria-label="Jump to month" className="min-h-10 rounded-xl border border-zinc-200 bg-white px-3 text-xs font-bold"/><button onClick={jump} disabled={!nextSaved} className="min-h-10 rounded-xl bg-[#FFF0E8] px-3 text-xs font-black text-[#B53A0A] disabled:opacity-40">Next saved</button><button onClick={()=>setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1))} className="min-h-10 rounded-xl border border-zinc-200 bg-white px-3 text-xs font-bold">Today</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="flex size-10 items-center justify-center rounded-xl border border-zinc-200 bg-white" aria-label="Previous month"><ChevronLeft className="size-5"/></button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="flex size-10 items-center justify-center rounded-xl border border-zinc-200 bg-white" aria-label="Next month"><ChevronRight className="size-5"/></button></div></div>
    <div className="hidden overflow-hidden rounded-[28px] border border-zinc-200 bg-white shadow-[0_20px_50px_rgba(28,28,26,.08)] md:block"><div className="grid grid-cols-7 bg-gradient-to-r from-zinc-950 to-[#3A1A0D] text-center text-[10px] font-black uppercase tracking-wider text-white">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d} className="p-3">{d}</div>)}</div><div className="grid grid-cols-7">{cells.map((day,i)=>{const daily=day?monthEvents.filter(e=>new Date(e.startDate).getDate()===day):[],today=day&&new Date().toDateString()===new Date(month.getFullYear(),month.getMonth(),day).toDateString();return <div key={i} className={`min-h-32 border-b border-r border-zinc-100 p-2 transition hover:bg-orange-50/30 ${daily.length?"bg-[#FFFCFA]":""}`}><span className={`flex size-6 items-center justify-center rounded-full text-[11px] font-bold ${today?"bg-[#D4450A] text-white":"text-zinc-400"}`}>{day}</span><div className="mt-2 space-y-1.5">{daily.map(e=><Link key={e.id} href={`/events/${e.slug}`} className="flex min-w-0 items-center gap-2 overflow-hidden rounded-xl border border-orange-100 bg-gradient-to-r from-[#FFF0E8] to-white p-1.5 shadow-sm hover:border-orange-300 hover:shadow-md">{e.coverImage?<img src={e.coverImage} alt="" className="size-8 shrink-0 rounded-lg object-cover"/>:<CalendarDays className="size-5 shrink-0 text-orange-400"/>}<span className="min-w-0"><strong className="block truncate text-[9px] text-[#9C310A]">{e.title}</strong><span className="block text-[8px] text-zinc-500">{new Date(e.startDate).toLocaleTimeString("en-TT",{hour:"numeric",minute:"2-digit"})}</span></span></Link>)}</div></div>})}</div></div>
    <section className="mt-6"><h2 className="font-black text-zinc-950">Events in {title}</h2><p className="mb-3 text-xs text-zinc-500">A clearer list of everything showing on the calendar</p>{monthEvents.length?<div className="grid gap-3 md:grid-cols-2">{monthEvents.map(e=><EventCard key={e.id} event={e}/>)}</div>:<div className="rounded-[24px] border border-dashed border-zinc-200 bg-white px-5 py-14 text-center"><CalendarDays className="mx-auto size-9 text-orange-300"/><p className="mt-3 text-sm font-bold text-zinc-800">No matching events in {title}</p><p className="mt-1 text-xs text-zinc-500">Change the filters, choose a month, or jump to your next saved event.</p></div>}</section>
  </div>;
}
