"use client";
import Link from "next/link";
import { useId, useRef, useState, useTransition, type ReactNode } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowDownWideNarrow, Check, ChevronDown, LocateFixed, RotateCcw, Search, SlidersHorizontal, X } from "lucide-react";
import { STORE_KINDS, STORE_SORTS, type StoreQuery } from "@/lib/stores/directory-query";
import type { StoreDirectoryOptions } from "@/lib/stores/directory";
import base from "@/components/shop/shop.module.css";
import styles from "./directory.module.css";

export function StoresSearch({value}:{value:string}){
  const [q,setQ]=useState(value),[pending,startTransition]=useTransition();const router=useRouter(),params=useSearchParams();
  return <form role="search" aria-label="Find a store" className={styles.search} onSubmit={event=>{event.preventDefault();const next=new URLSearchParams(params.toString());next.delete("page");if(q.trim())next.set("q",q.trim());else next.delete("q");startTransition(()=>router.push(`/stores${next.size?"?"+next:""}#store-results`,{scroll:false}));}}><Search size={18} aria-hidden/><input type="search" aria-label="Search stores" placeholder="A name, a passion, a place…" value={q} onChange={event=>setQ(event.target.value)}/><button disabled={pending} type="submit">{pending?"Finding…":"Search"}</button></form>;
}
export default function StoresBrowser({query,options,total,children}:{query:StoreQuery;options:StoreDirectoryOptions;total:number;children:ReactNode}){
  const router=useRouter(),params=useSearchParams(),id=useId(),dialog=useRef<HTMLDialogElement>(null);
  const initial={category:query.category,region:query.region,kind:query.kind,tag:query.tag};
  const [draft,setDraft]=useState(initial),[pending,startTransition]=useTransition(),[locating,setLocating]=useState(false),[error,setError]=useState("");
  const count=Object.values(initial).filter(Boolean).length;
  function navigate(values:Record<string,string>){const next=new URLSearchParams(params.toString());next.delete("page");for(const [key,value] of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}dialog.current?.close();startTransition(()=>router.push(`/stores${next.size?"?"+next:""}#store-results`,{scroll:false}));}
  function locate(){setError("");if(!navigator.geolocation){setError("Location isn’t available here. Choose an area instead.");return;}setLocating(true);navigator.geolocation.getCurrentPosition(position=>{setLocating(false);navigate({lat:position.coords.latitude.toFixed(5),lng:position.coords.longitude.toFixed(5),sort:"nearest"});},()=>{setLocating(false);setError("We couldn’t get your location. Allow location access or choose an area above.");},{timeout:10000,maximumAge:300000});}
  function fields(prefix:string){
    const select=(key:keyof typeof draft,label:string,values:{value:string;label:string}[],placeholder:string)=><label className={base.field} htmlFor={prefix+key}><span>{label}</span><div className={base.selectWrap}><select id={prefix+key} value={draft[key]} onChange={event=>setDraft({...draft,[key]:event.target.value})}><option value="">{placeholder}</option>{draft[key]&&!values.some(v=>v.value===draft[key])&&<option value={draft[key]}>{draft[key].replaceAll("_"," ")}</option>}{values.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select><ChevronDown size={14} aria-hidden/></div></label>;
    return <form className={base.filterForm} onSubmit={event=>{event.preventDefault();navigate(draft);}}>{select("category","Store category",options.categories.map(c=>({...c,label:`${c.label} (${c.count})`})),"Every kind of business")}{select("region","Where in T&T?",options.regions,"All areas")}{select("kind","What are you looking for?",STORE_KINDS,"A little of everything")}{options.tags.length>0&&select("tag","Something specific",options.tags.map(tag=>({value:tag,label:tag})),"All interests")}<div><button type="button" className={styles.locationButton} onClick={locate} disabled={locating||pending}><LocateFixed size={16} aria-hidden/>{locating?"Finding your location…":"Find stores near me"}</button><p className={styles.locationNote}>Use your location for approximate distances. Stores without a saved map pin appear after nearby matches.</p>{error&&<p className={styles.locationError} role="alert">{error}</p>}{query.lat!==null&&<button type="button" className={styles.locationButton} onClick={()=>navigate({lat:"",lng:"",sort:query.sort==="nearest"?"recommended":query.sort})}>Clear my location</button>}</div><div className={base.filterActions}><button type="submit" disabled={pending}>{pending?"Updating…":"Apply filters"}<Check size={16} aria-hidden/></button><button type="button" onClick={()=>navigate({category:"",region:"",kind:"",tag:"",lat:"",lng:"",sort:""})} disabled={pending}><RotateCcw size={13} aria-hidden/>Reset filters</button></div></form>;
  }
  return <div className={base.browseLayout} aria-busy={pending}><aside className={base.sidebar} aria-label="Store filters"><div className={base.filterHeading}><SlidersHorizontal size={18} aria-hidden/><div><h3>Your kind of local.</h3><p>A few ways to find it.</p></div></div>{fields(id+"desktop")}<div className={base.sidebarNote}><span>BIG DREAMS. CLOSE TO HOME.</span><strong>Find a favourite.<br/>Follow their story.</strong><Link href="/saved-stores">See stores you follow ↗</Link></div></aside><div className={base.resultsColumn}><div className={base.toolbar}><button type="button" className={base.filterTrigger} aria-haspopup="dialog" onClick={()=>{setDraft(initial);setError("");dialog.current?.showModal();}}><SlidersHorizontal size={17} aria-hidden/>Filters{count>0&&<span>{count}</span>}</button><p className={base.resultCount} role="status">{pending?"Finding your stores…":`${total} ${total===1?"store":"stores"} to discover`}</p><label className={base.sortLabel} htmlFor={id+"sort"}><ArrowDownWideNarrow size={17} aria-hidden/><span>Sort by</span><select id={id+"sort"} aria-label="Sort stores" value={query.sort} disabled={pending} onChange={event=>navigate({sort:event.target.value})}>{STORE_SORTS.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select><ChevronDown size={13} aria-hidden/></label></div>{query.sort==="nearest"&&query.lat===null&&<p className={styles.locationNote}>Choose “Find stores near me” in Filters to sort by distance. Recommended stores are shown until a location is available.</p>}<div className={base.resultsBody} data-pending={pending}>{children}</div></div><dialog ref={dialog} className={base.filterDialog} aria-labelledby={id+"title"} onClick={event=>{if(event.target===event.currentTarget){const rect=event.currentTarget.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.current?.close();}}}><div className={base.dialogHeading}><div><span>FIND YOUR KIND OF LOCAL</span><h2 id={id+"title"}>Discover your stores</h2></div><button aria-label="Close filters" type="button" onClick={()=>dialog.current?.close()}><X size={23} aria-hidden/></button></div>{fields(id+"mobile")}</dialog></div>;
}
