import type { Metadata } from "next";
import { Playfair_Display, Sora } from "next/font/google";

import CartProvider from "@/components/cart/CartProvider";
import InstallPrompt from "@/components/pwa/InstallPrompt";
import ServiceWorkerRegistration from "@/components/pwa/ServiceWorkerRegistration";

import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#D4450A",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "LinkWe Online Mall",
  },
  formatDetection: {
    telephone: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sora.variable} ${playfair.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ServiceWorkerRegistration />
        <InstallPrompt />
        <CartProvider>{children}</CartProvider>
        <footer className="border-t border-zinc-200 bg-white py-8">
          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-between">
              <p className="text-xs text-zinc-400">
                © {new Date().getFullYear()} LinkWe Online Directory. All rights reserved.
              </p>
              <div className="flex items-center gap-6">
                <a href="/privacy" className="text-xs text-zinc-400 hover:text-zinc-600 transition-colors">
                  Privacy Policy
                </a>
                <a href="/terms" className="text-xs text-zinc-400 hover:text-zinc-600 transition-colors">
                  Terms of Service
                </a>
                <a href="/contact" className="text-xs text-zinc-400 hover:text-zinc-600 transition-colors">
                  Contact
                </a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
