"use client";
import { useId, useRef, useState } from "react";
import { Tag, X } from "lucide-react";
import { previewStoreCoupon } from "@/app/actions/store-coupons";
export type AppliedCoupon={code:string;discountMinor:number;totalMinor:number};
export default function CouponInput({kind,id,onChange,value,disabled=false,subscription=false}:{kind:"cart"|"service"|"request";id?:string;onChange:(coupon:AppliedCoupon|null)=>void;value?:AppliedCoupon|null;disabled?:boolean;subscription?:boolean}){
 const inputId=useId();const [input,setInput]=useState("");const [internalApplied,setApplied]=useState<AppliedCoupon|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const version=useRef(0);
 const applied=value===undefined?internalApplied:value;
 function clear(){version.current++;setInput("");setApplied(null);setError("");onChange(null);}
 async function apply(){if(!input.trim()||busy)return;const current=++version.current;setBusy(true);setError("");try{const result=await previewStoreCoupon({kind,id,code:input});if(current!==version.current)return;if(!result.ok){setError(result.error);setApplied(null);onChange(null);return;}setInput(result.code);setApplied(result);onChange(result);}catch{setError("Could not check the code. Please try again.");}finally{setBusy(false);}}
 return <div className="my-3 rounded-xl border border-orange-100 bg-orange-50/50 p-3 text-xs"><label htmlFor={inputId} className="mb-2 flex items-center gap-2 font-bold text-[#a54116]"><Tag size={14}/> Have a coupon?</label>{applied?<div className="flex items-center justify-between gap-3 text-emerald-800"><span><strong>{applied.code}</strong> · Save TTD {(applied.discountMinor/100).toFixed(2)}</span><button type="button" onClick={clear} disabled={disabled||busy} aria-label="Remove coupon" className="grid size-9 shrink-0 place-items-center rounded-lg bg-white"><X size={16}/></button></div>:<div className="flex gap-2"><input id={inputId} value={input} maxLength={30} disabled={disabled||busy} autoCapitalize="characters" placeholder="Enter code" className="min-w-0 flex-1 rounded-lg border border-orange-200 bg-white px-3 py-2.5 text-sm text-zinc-800 outline-none focus:ring-2 focus:ring-orange-200" onChange={event=>{setInput(event.target.value);setError("");}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void apply();}}}/><button type="button" disabled={disabled||busy||!input.trim()} onClick={()=>void apply()} className="rounded-lg bg-[#d94308] px-3 font-bold text-white disabled:opacity-50">{busy?"Checking…":"Apply"}</button></div>}{error&&<p role="alert" className="mt-2 leading-5 text-red-700">{error}</p>}{applied&&subscription&&<p className="mt-2 leading-5 text-zinc-500">Discount applies to this checkout payment. Future renewals keep the regular price.</p>}{applied&&kind==="cart"&&<p className="mt-2 leading-5 text-zinc-500">Applied to eligible products from participating stores. Delivery is unchanged.</p>}</div>;
}
