"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowRight,Bell,CheckCheck,X} from "lucide-react";
import {getNotificationPage,markAllNotificationsRead,markNotificationRead} from "@/app/actions/notifications";
import {safeNotificationHref,type NotificationItem} from "@/lib/notifications/display";
import {NotificationRow} from "@/components/notifications/NotificationCentre";
import s from "@/components/notifications/notifications.module.css";
export default function NotificationBell({initialUnreadCount,variant="light",compactToolbar=false}:{initialUnreadCount:number;variant?:"light"|"dark";compactToolbar?:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),[open,setOpen]=useState(false),[unread,setUnread]=useState(false),[count,setCount]=useState(initialUnreadCount),[data,setData]=useState<Awaited<ReturnType<typeof getNotificationPage>>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const seq=useRef(0);
 const load=useCallback(async()=>{const request=++seq.current;try{const next=await getNotificationPage({unread});if(request===seq.current){setData(next);setCount(next.unread);setError("");}}catch{if(request===seq.current)setError("We couldn’t load your notifications.");}},[unread]);
 useEffect(()=>{if(open){dialog.current?.showModal();void load();}else dialog.current?.close();},[open,load]);
 useEffect(()=>{const update=()=>{if(document.visibilityState==="visible")void load();};window.addEventListener("linkwe-notifications:changed",update);const interval=setInterval(update,30000);return()=>{seq.current++;clearInterval(interval);window.removeEventListener("linkwe-notifications:changed",update);};},[load]);
 async function read(item:NotificationItem){setBusy(true);try{if(!item.isRead)await markNotificationRead(item.id);const href=safeNotificationHref(item.linkUrl);if(href){setOpen(false);window.location.assign(href);}else await load();window.dispatchEvent(new Event("linkwe-notifications:changed"));}catch{setError("Couldn’t open this update. Please try again.");}finally{setBusy(false);}}
 async function allRead(){setBusy(true);try{await markAllNotificationsRead(data?.snapshot);await load();window.dispatchEvent(new Event("linkwe-notifications:changed"));}catch{setError("Couldn’t update your notifications.");}finally{setBusy(false);}}
 return <><button type="button" onClick={()=>setOpen(true)} aria-label="Notifications" aria-haspopup="dialog" aria-expanded={open} className={`relative flex items-center justify-center rounded-xl transition-colors ${compactToolbar?"h-8 w-8":"h-10 w-10"} ${variant==="dark"?"text-zinc-200 hover:bg-white/10":"text-[#174766] hover:bg-orange-50"}`}><Bell size={compactToolbar?18:20}/>{count>0&&<span className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-[#D4450A] px-1 text-[9px] font-bold text-white">{count>99?"99+":count}</span>}</button><dialog ref={dialog} className={s.panel} aria-label="Notifications" onClose={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setOpen(false);}}}><div className={s.panelInner}><header><div><small>YOU’RE IN THE LOOP</small><h2>Your updates <span className="text-orange-200">{count?`· ${count}`:""}</span></h2></div><button aria-label="Close notifications" onClick={()=>setOpen(false)}><X size={19}/></button></header><div className={s.toolbar}><div className={s.tabs}><button aria-pressed={!unread} onClick={()=>setUnread(false)}>All</button><button aria-pressed={unread} onClick={()=>setUnread(true)}>Unread</button></div><button onClick={()=>void allRead()} disabled={busy||!count}><CheckCheck size={15}/>Read all</button></div>{error&&<p className={s.error} role="alert">{error}<button onClick={()=>void load()}>Retry</button></p>}<div className={s.panelList} aria-busy={busy}>{!data?<p className={s.empty}>Loading your updates…</p>:data.items.length?data.items.slice(0,8).map(item=><NotificationRow key={item.id} item={item} onRead={read}/>):<div className={s.empty}><Bell size={32}/><h2>You’re all caught up.</h2><p>New updates will appear here.</p></div>}</div><footer><Link href="/notifications" onClick={()=>setOpen(false)}>Open all notifications <ArrowRight size={15}/></Link><button onClick={()=>window.dispatchEvent(new CustomEvent("linkwe-push:prompt"))}>Device alerts</button></footer></div></dialog></>;
}
