"use client";
import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, ArrowUpRight, CheckCheck, ChevronLeft, ChevronRight, Download, Package, PackageCheck, RefreshCw, Search, SlidersHorizontal, ShoppingBag, Truck, X } from "lucide-react";
import { customerDate, customerOrderBucket, customerOrderState, filterCustomerOrders, orderReference, type CustomerOrder, type OrderView } from "@/lib/customer/orders";
import { formatTTDMinor } from "@/lib/format/price";
import CustomerPageIntro from "@/components/customer/CustomerPageIntro";
import OrderProgress from "@/components/customer/OrderProgress";
import styles from "@/components/customer/customer.module.css";
export default function OrdersClient({orders}:{orders:CustomerOrder[]}) {
 const router=useRouter();const [pending,startTransition]=useTransition();
 const [search,setSearch]=useState("");const [view,setView]=useState<OrderView>("all");const [status,setStatus]=useState("all");const [sort,setSort]=useState("newest");const [days,setDays]=useState(0);const [page,setPage]=useState(1);
 const filtered=useMemo(()=>filterCustomerOrders(orders,{search,view,status,sort,days}),[orders,search,view,status,sort,days]);
 const pages=Math.max(1,Math.ceil(filtered.length/6));const currentPage=Math.min(page,pages);const visible=filtered.slice((currentPage-1)*6,currentPage*6);
 const tabs=[{id:"all",label:"All orders",icon:ShoppingBag},{id:"active",label:"In progress",icon:Truck},{id:"delivered",label:"Delivered & complete",icon:CheckCheck},{id:"closed",label:"Closed",icon:Package}] as const;
 const reset=()=>{setSearch("");setView("all");setStatus("all");setDays(0);setSort("newest");setPage(1);};
 return <><CustomerPageIntro page="orders" count={orders.length}/><section className={styles.orderWorkspace} aria-label="Your orders"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>YOUR SHOPPING STORY</span><h2>From “love it” to <em>got it.</em></h2></div><button className={styles.secondary} disabled={pending} onClick={()=>startTransition(()=>router.refresh())}><RefreshCw size={16} className={pending?styles.spin:undefined}/>{pending?"Refreshing…":"Refresh"}</button></div>
 <div className={styles.filterTabs} aria-label="Filter orders">{tabs.map(tab=><button key={tab.id} aria-pressed={view===tab.id} onClick={()=>{setView(tab.id);setStatus("all");setPage(1);}}><tab.icon size={17}/>{tab.label}<span>{tab.id==="all"?orders.length:orders.filter(order=>customerOrderBucket(order.status)===tab.id).length}</span></button>)}</div>
 <div className={styles.toolbar}><label className={styles.search}><Search size={19}/><input aria-label="Search your orders" placeholder="Order number, item or store…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{search&&<button onClick={()=>{setSearch("");setPage(1);}} aria-label="Clear search"><X size={16}/></button>}</label><label className={styles.select}><SlidersHorizontal size={16}/><select aria-label="Order status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All statuses</option>{[...new Set(orders.map(order=>order.status))].map(value=><option key={value} value={value}>{value.toLowerCase().replaceAll("_"," ")}</option>)}</select></label><select className={styles.select} aria-label="Order date range" value={days} onChange={e=>{setDays(Number(e.target.value));setPage(1);}}><option value={0}>Any time</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option></select><select className={styles.select} aria-label="Sort orders" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="highest">Highest total</option><option value="lowest">Lowest total</option></select></div>
 <div className={styles.resultLine} aria-live="polite"><span>{filtered.length} {filtered.length===1?"order":"orders"}{search?` matching “${search}”`:""}</span>{(search||view!=="all"||status!=="all"||days!==0||sort!=="newest")&&<button onClick={reset}>Reset filters<X size={13}/></button>}</div>
 {visible.length===0?<div className={styles.empty}><span><PackageCheck size={36}/></span><h2>{orders.length?"No finds here just yet.":"Your story starts with a good find."}</h2><p>{orders.length?"Try another item, store or order number, or reset your filters.":"Once you place an order, its progress and details will live right here."}</p>{orders.length?<button className={styles.primary} onClick={reset}>Reset filters<ArrowRight size={17}/></button>:<Link className={styles.primary} href="/shop">Find your first favourite<ArrowUpRight size={17}/></Link>}</div>:<div className={styles.orderGrid}>{visible.map(order=>{const state=customerOrderState(order);const count=order.items.reduce((sum,item)=>sum+item.quantity,0);const stores=[...new Set(order.items.map(item=>item.store.name))];return <article className={styles.orderCard} key={order.id}><header><div><Link href={`/orders/${order.id}`} className={styles.reference}>{orderReference(order)}</Link><time dateTime={new Date(order.createdAt).toISOString()}>{customerDate(order.createdAt)}</time></div><span className={styles.status} data-tone={state.tone}><span/>{state.label}</span></header><div className={styles.orderPreview}><div className={styles.imageStack}>{order.items.slice(0,3).map(item=><span key={item.id}>{item.product?.images[0]?<img src={item.product.images[0]} alt=""/>:<Package size={28}/>}</span>)}{order.items.length>3&&<span className={styles.moreImages}>+{order.items.length-3}</span>}</div><div><p className={styles.storeCaption}>{stores.join(" · ")||"Your local stores"}</p><h3><Link href={`/orders/${order.id}`}>{order.items[0]?.titleSnapshot??"Your LinkWe order"}{order.items.length>1&&<small> +{order.items.length-1} more</small>}</Link></h3><p className={styles.muted}>{count} {count===1?"item":"items"} · {state.digital?"Digital delivery":state.pickup?"Warehouse pickup":"Delivery"}</p></div></div><OrderProgress steps={state.steps} current={state.step}/><p className={styles.orderHint}>{state.detail}</p><footer><div><small>Order total</small><strong>{formatTTDMinor(order.totalMinor)}</strong></div><div className={styles.cardActions}><a href={`/api/invoice/${order.id}`} className={styles.invoice} aria-label={`Download invoice for ${orderReference(order)}`}><Download size={17}/><span>Invoice</span></a><Link href={`/orders/${order.id}`} className={styles.primary}>{order.status==="DELIVERED"?"Confirm receipt":state.digital?"View downloads":"View order"}<ArrowRight size={16}/></Link></div></footer></article>;})}</div>}
 {pages>1&&<nav className={styles.pagination} aria-label="Order pages"><span>Page {currentPage} of {pages}</span><div><button className={styles.secondary} disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={18}/>Previous</button><button className={styles.secondary} disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next<ChevronRight size={18}/></button></div></nav>}
 </section><div className={styles.helpStrip}><PackageCheck size={25}/><div><strong>A little help goes a long way.</strong><p>Questions about a delivery or order? We’re here.</p></div><Link href="/contact">Get in touch<ArrowUpRight size={17}/></Link></div></>;
}
