// Product categories — used across shop, store tab, vendor AI, and admin
export const PRODUCT_CATEGORIES = [
  { value: "accessories", label: "Accessories" },
  { value: "alcohol_spirits", label: "Alcohol & Spirits" },
  { value: "appliances", label: "Appliances" },
  { value: "art_crafts", label: "Art & Crafts" },
  { value: "audio_headphones", label: "Audio & Headphones" },
  { value: "automotive_parts", label: "Automotive Parts" },
  { value: "baby_clothing", label: "Baby Clothing" },
  { value: "baby_products", label: "Baby Products" },
  { value: "bags_luggage", label: "Bags & Luggage" },
  { value: "bakery_pastries", label: "Bakery & Pastries" },
  { value: "bedding_bath", label: "Bedding & Bath" },
  { value: "beverages_drinks", label: "Beverages & Drinks" },
  { value: "boat_accessories", label: "Boat & Marine Accessories" },
  { value: "books_stationery", label: "Books & Stationery" },
  { value: "business_services", label: "Business Services" },
  { value: "cameras_photography", label: "Cameras & Photography" },
  { value: "car_accessories", label: "Car Accessories" },
  { value: "carnival_costumes", label: "Carnival & Costumes" },
  { value: "carnival_accessories", label: "Carnival Accessories" },
  { value: "christmas_supplies", label: "Christmas & Holiday Supplies" },
  { value: "church_supplies", label: "Church & Religious Supplies" },
  { value: "cleaning_supplies", label: "Cleaning Supplies" },
  { value: "clothing_apparel", label: "Clothing & Apparel" },
  { value: "computers_laptops", label: "Computers & Laptops" },
  { value: "condiments_pepper_sauce", label: "Condiments & Pepper Sauce" },
  { value: "cycling", label: "Cycling" },
  { value: "dairy_eggs", label: "Dairy & Eggs" },
  { value: "digital_products", label: "Digital Products" },
  { value: "divali_supplies", label: "Divali & Hindu Supplies" },
  { value: "eid_supplies", label: "Eid & Islamic Supplies" },
  { value: "electronics", label: "Electronics" },
  { value: "farming_supplies", label: "Farming & Agricultural Supplies" },
  { value: "fishing_supplies", label: "Fishing Supplies & Equipment" },
  { value: "flags_banners", label: "Flags & Banners" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "fragrances_perfumes", label: "Fragrances & Perfumes" },
  { value: "fresh_produce", label: "Fresh Produce & Vegetables" },
  { value: "gaming", label: "Gaming" },
  { value: "garden_outdoor", label: "Garden & Outdoor" },
  { value: "gift_cards", label: "Gift Cards & Vouchers" },
  { value: "gym_equipment", label: "Gym Equipment" },
  { value: "haircare", label: "Hair Care & Products" },
  { value: "handmade", label: "Handmade & Custom" },
  { value: "health_beauty", label: "Health & Beauty" },
  { value: "home_furniture", label: "Home & Furniture" },
  { value: "home_decor", label: "Home Decor & Accessories" },
  { value: "jewellery_watches", label: "Jewellery & Watches" },
  { value: "kids_clothing", label: "Kids Clothing" },
  { value: "kids_education", label: "Kids Education" },
  { value: "kitchen_dining", label: "Kitchen & Dining" },
  { value: "lighting", label: "Lighting" },
  { value: "local_food", label: "Local & Trinidadian Food" },
  { value: "makeup_cosmetics", label: "Makeup & Cosmetics" },
  { value: "martial_arts", label: "Martial Arts" },
  { value: "meal_prep_catering", label: "Meal Prep & Catering" },
  { value: "meat_poultry", label: "Meat & Poultry" },
  { value: "medical_supplies", label: "Medical Supplies" },
  { value: "music_instruments", label: "Music & Instruments" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "organic_natural", label: "Organic & Natural Foods" },
  { value: "outdoor_sports", label: "Outdoor & Water Sports" },
  { value: "paint_materials", label: "Paint & Building Materials" },
  { value: "personal_care", label: "Personal Care" },
  { value: "phone_cases", label: "Phone Cases & Covers" },
  { value: "phones_accessories", label: "Phones & Accessories" },
  { value: "photography_art", label: "Photography & Prints" },
  { value: "pool_supplies", label: "Pool Supplies" },
  { value: "printing_branding", label: "Printing & Branding" },
  { value: "roti_doubles", label: "Roti, Doubles & Street Food" },
  { value: "safety_equipment", label: "Safety & PPE Equipment" },
  { value: "school_uniforms", label: "School Uniforms" },
  { value: "seafood_fish", label: "Seafood & Fish" },
  { value: "shoes_footwear", label: "Shoes & Footwear" },
  { value: "skincare", label: "Skincare" },
  { value: "smart_home", label: "Smart Home Devices" },
  { value: "snacks_confectionery", label: "Snacks & Confectionery" },
  { value: "solar_panels", label: "Solar Panels & Equipment" },
  { value: "spa_wellness", label: "Spa & Wellness" },
  { value: "spices_sauces", label: "Spices, Sauces & Seasonings" },
  { value: "sports_fitness", label: "Sports & Fitness" },
  { value: "sportswear_activewear", label: "Sportswear & Activewear" },
  { value: "storage_organisation", label: "Storage & Organisation" },
  { value: "subscriptions", label: "Subscriptions" },
  { value: "swimwear_beachwear", label: "Swimwear & Beachwear" },
  { value: "team_sports", label: "Team Sports" },
  { value: "tickets_events", label: "Tickets & Events" },
  { value: "tools_hardware", label: "Tools & Hardware" },
  { value: "toys_games", label: "Toys & Games" },
  { value: "traditional_cultural", label: "Traditional & Cultural Wear" },
  { value: "trophies_awards", label: "Trophies & Awards" },
  { value: "tv_entertainment", label: "TV & Entertainment" },
  { value: "tyres_wheels", label: "Tyres & Wheels" },
  { value: "underwear_lingerie", label: "Underwear & Lingerie" },
  { value: "uniforms_embroidery", label: "Uniforms & Embroidery" },
  { value: "veterinary_supplies", label: "Veterinary Supplies" },
  { value: "vitamins_supplements", label: "Vitamins & Supplements" },
  { value: "waist_beads_jewelry", label: "Waist Beads & Cultural Jewelry" },
  { value: "workwear_uniforms", label: "Workwear & Uniforms" },
] as const;

// Store/business categories — used in store discovery and vendor onboarding
export const STORE_CATEGORIES = [
  { value: "ac_appliance_repair", label: "AC & Appliance Repair" },
  { value: "accounting_tax", label: "Accounting & Tax" },
  { value: "agriculture_farming", label: "Agriculture & Farming" },
  { value: "airbnb_shortterm", label: "Airbnb & Short-term Rental" },
  { value: "art_crafts_handmade", label: "Art, Crafts & Handmade" },
  { value: "automotive", label: "Automotive" },
  { value: "bakery_pastry", label: "Bakery & Pastry" },
  { value: "bar_lounge", label: "Bar & Lounge" },
  { value: "beauty_wellness", label: "Beauty & Wellness" },
  { value: "boat_marine", label: "Boat & Marine" },
  { value: "books_stationery", label: "Books & Stationery" },
  { value: "car_rental", label: "Car Rental" },
  { value: "car_wash_detailing", label: "Car Wash & Detailing" },
  { value: "carnival_mas", label: "Carnival & Mas" },
  { value: "catering_services", label: "Catering Services" },
  { value: "childcare_nursery", label: "Childcare & Nursery" },
  { value: "church_religious", label: "Church & Religious Organisation" },
  { value: "cleaning_services", label: "Cleaning Services" },
  { value: "construction_hardware", label: "Construction & Hardware" },
  { value: "courier_delivery", label: "Courier & Delivery" },
  { value: "dance_studio", label: "Dance Studio" },
  { value: "dental_medical", label: "Dental & Medical" },
  { value: "digital_services", label: "Digital Services" },
  { value: "dj_entertainment", label: "DJ & Entertainment" },
  { value: "driving_school", label: "Driving School" },
  { value: "education_tutoring", label: "Education & Tutoring" },
  { value: "electronics_tech", label: "Electronics & Tech" },
  { value: "electronics_repair", label: "Electronics Repair" },
  { value: "embassy_consulate", label: "Embassy & Consulate" },
  { value: "event_rentals", label: "Event Rentals & Decor" },
  { value: "events_planning", label: "Events & Planning" },
  { value: "farm_agriculture", label: "Farm & Agriculture" },
  { value: "fashion_apparel", label: "Fashion & Apparel" },
  { value: "fishery_seafood", label: "Fishery & Seafood" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "general_retail", label: "General Retail" },
  { value: "government_services", label: "Government Services" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "grocery_supermarket", label: "Grocery & Supermarket" },
  { value: "gym_fitness_centre", label: "Gym & Fitness Centre" },
  { value: "health_pharmacy", label: "Health & Pharmacy" },
  { value: "home_furniture", label: "Home & Furniture" },
  { value: "hospitality_hotel", label: "Hospitality & Hotel" },
  { value: "hotel_guesthouse", label: "Hotel & Guesthouse" },
  { value: "insurance", label: "Insurance" },
  { value: "investment_trading", label: "Investment & Trading" },
  { value: "jewellery_accessories", label: "Jewellery & Accessories" },
  { value: "jewellery_repair", label: "Jewellery Repair" },
  { value: "landscaping_gardening", label: "Landscaping & Gardening" },
  { value: "language_school", label: "Language School" },
  { value: "laundry_dry_cleaning", label: "Laundry & Dry Cleaning" },
  { value: "legal_financial", label: "Legal & Financial Services" },
  { value: "lumber_building_materials", label: "Lumber & Building Materials" },
  { value: "marketing_advertising", label: "Marketing & Advertising" },
  { value: "martial_arts_studio", label: "Martial Arts Studio" },
  { value: "mechanic_garage", label: "Mechanic & Garage" },
  { value: "media_production", label: "Media & Video Production" },
  { value: "medical_equipment", label: "Medical Equipment" },
  { value: "mortgage_loans", label: "Mortgage & Loans" },
  { value: "music_entertainment", label: "Music & Entertainment" },
  { value: "nail_spa", label: "Nail & Spa" },
  { value: "ngo_charity", label: "NGO & Charity" },
  { value: "nightclub_entertainment", label: "Nightclub & Entertainment" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "optical_eyewear", label: "Optical & Eyewear" },
  { value: "painting_contractor", label: "Painting & Contractor" },
  { value: "pest_control", label: "Pest Control" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "pharmacy_drugstore", label: "Pharmacy & Drugstore" },
  { value: "photography_studio", label: "Photography & Studio" },
  { value: "plumbing_electrical", label: "Plumbing & Electrical" },
  { value: "pool_spa_services", label: "Pool & Spa Services" },
  { value: "printing_branding", label: "Printing & Branding" },
  { value: "real_estate", label: "Real Estate" },
  { value: "recording_studio", label: "Recording Studio" },
  { value: "religious_spiritual", label: "Religious & Spiritual" },
  { value: "restaurant_cafe", label: "Restaurant & Café" },
  { value: "salon_barbershop", label: "Salon & Barbershop" },
  { value: "school_academy", label: "School & Academy" },
  { value: "security_services", label: "Security Services" },
  { value: "shipping_freight", label: "Shipping & Freight" },
  { value: "shoe_repair", label: "Shoe Repair" },
  { value: "solar_energy", label: "Solar & Renewable Energy" },
  { value: "sports_fitness", label: "Sports & Fitness" },
  { value: "storage_warehouse", label: "Storage & Warehouse" },
  { value: "tailoring_alterations", label: "Tailoring & Alterations" },
  { value: "tattoo_piercing", label: "Tattoo & Piercing" },
  { value: "tinting_wrapping", label: "Tinting & Wrapping" },
  { value: "toys_kids", label: "Toys & Kids" },
  { value: "travel_tours", label: "Travel & Tours" },
  { value: "vehicles", label: "Vehicles" },
  { value: "veterinary_pet", label: "Veterinary & Pet Care" },
  { value: "waste_management", label: "Waste Management & Recycling" },
  { value: "web_design_it", label: "Web Design & IT" },
  { value: "wedding_services", label: "Wedding Services" },
  { value: "yoga_pilates", label: "Yoga & Pilates" },
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number]["value"];
export type StoreCategory = (typeof STORE_CATEGORIES)[number]["value"];

// Helper to get label from value
export function getProductCategoryLabel(value: string): string {
  return PRODUCT_CATEGORIES.find((c) => c.value === value)?.label ?? value.replace(/_/g, " ");
}

export function getStoreCategoryLabel(value: string): string {
  return STORE_CATEGORIES.find((c) => c.value === value)?.label ?? value.replace(/_/g, " ");
}

export const SERVICE_CATEGORIES = [
  { value: "beauty_hair", label: "Beauty & Hair" },
  { value: "health_wellness", label: "Health & Wellness" },
  { value: "fitness_training", label: "Fitness & Training" },
  { value: "home_services", label: "Home Services" },
  { value: "cleaning_services", label: "Cleaning Services" },
  { value: "repairs_maintenance", label: "Repairs & Maintenance" },
  { value: "automotive_services", label: "Automotive Services" },
  { value: "food_catering", label: "Food & Catering" },
  { value: "education_tutoring", label: "Education & Tutoring" },
  { value: "photography_video", label: "Photography & Video" },
  { value: "design_branding", label: "Graphic Design & Branding" },
  { value: "web_tech", label: "Web & Tech Services" },
  { value: "legal_financial", label: "Legal & Financial" },
  { value: "events_entertainment", label: "Events & Entertainment" },
  { value: "music_dj", label: "Music & DJ" },
  { value: "security_services", label: "Security Services" },
  { value: "childcare", label: "Childcare & Babysitting" },
  { value: "pet_care", label: "Pet Care" },
  { value: "courier_delivery", label: "Courier & Delivery" },
  { value: "tailoring_alterations", label: "Tailoring & Alterations" },
  { value: "printing_signage", label: "Printing & Signage" },
  { value: "construction_renovation", label: "Construction & Renovation" },
  { value: "landscaping_gardening", label: "Landscaping & Gardening" },
  { value: "travel_tours", label: "Travel & Tours" },
  { value: "spiritual_wellness", label: "Spiritual & Wellness" },
] as const;

export type ServiceCategory = (typeof SERVICE_CATEGORIES)[number]["value"];

export function getServiceCategoryLabel(value: string): string {
  return SERVICE_CATEGORIES.find((c) => c.value === value)?.label ?? value.replace(/_/g, " ");
}
