import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, CalendarDays, ConciergeBell, Grid2X2, Heart, MapPin, Package, ShieldCheck, Store, X } from "lucide-react";
import PublicNav from "@/components/layout/PublicNav";
import StoresHero from "@/components/stores/StoresHero";
import StoreDirectoryCard from "@/components/stores/StoreDirectoryCard";
import StoresBrowser, { StoresSearch } from "@/components/stores/StoresBrowser";
import StoresMap from "@/components/stores/StoresMap";
import { getStoreDirectory } from "@/lib/stores/directory";
import { parseStoreQuery, storesHref, storeCategory, STORE_KINDS, STORE_PAGE_SIZE, type StoreParams } from "@/lib/stores/directory-query";
import { getSavedStoreIds } from "@/app/actions/wishlist";
import { getRoleDashboardPath } from "@/lib/auth/redirects";
import { getSession } from "@/lib/auth/session";
import { getNavUnreadCount } from "@/lib/notifications/get-unread-count";
import { getRegionLabel } from "@/lib/regions/tt-regions";
import { prisma } from "@/lib/prisma";
import base from "@/components/shop/shop.module.css";
import styles from "@/components/stores/directory.module.css";

export const metadata:Metadata={title:"Discover local stores",description:"Meet the people behind your next favourite. Explore independent shops, service providers and event organisers across Trinidad & Tobago on LinkWe."};
export default async function StoresDiscoveryPage({searchParams}:{searchParams:Promise<StoreParams>}){
  const params=await searchParams,query=parseStoreQuery(params);
  const [session,unreadCount,catalog,saved]=await Promise.all([getSession(),getNavUnreadCount(),getStoreDirectory(query),getSavedStoreIds()]);
  const user=session?await prisma.user.findUnique({where:{id:session.userId},select:{fullName:true,role:true}}):null,dashboard=user?getRoleDashboardPath(user.role):undefined;
  const chips=[...(query.q?[{key:"q",label:`Search: ${query.q}`}]:[]),...(query.category?[{key:"category",label:storeCategory(query.category)}]:[]),...(query.region?[{key:"region",label:getRegionLabel(query.region)}]:[]),...(query.tag?[{key:"tag",label:query.tag}]:[]),...(query.kind?[{key:"kind",label:STORE_KINDS.find(k=>k.value===query.kind)!.label}]:[])];
  const kindIcons=[Package,ConciergeBell,CalendarDays];
  return <div className={base.page}><PublicNav user={user?{name:user.fullName??"Account",href:dashboard!}:null} dashboardHref={dashboard} unreadCount={unreadCount}/>{catalog.preview&&<div className={base.previewNote}>Local design preview · Real LinkWe store examples · Store links open the live site</div>}<main><div className={base.container}><StoresHero stores={catalog.highlights}/><div className={styles.introBar}><p><MapPin size={16} aria-hidden/>Rooted in Trinidad &amp; Tobago. Open to possibility.</p><nav className={styles.kindLinks} aria-label="Ways to discover stores">{STORE_KINDS.map((kind,i)=>{const Icon=kindIcons[i];return <Link key={kind.value} href={storesHref(params,{kind:query.kind===kind.value?undefined:kind.value,page:undefined})} aria-current={query.kind===kind.value?"page":undefined}><Icon size={15} aria-hidden/>{kind.label}</Link>;})}</nav></div></div>
    <section id="store-results" className={`${base.container} ${styles.catalog}`} aria-labelledby="store-results-title"><div className={base.sectionHeading}><div><p className={base.eyebrow}>SMALL BUSINESSES. BIG PERSONALITIES.</p><h2 id="store-results-title">{query.q?<>Your search. <em>Your local.</em></>:query.category?storeCategory(query.category):<>Find a store. <em>Feel a connection.</em></>}</h2></div><StoresSearch key={query.q} value={query.q}/></div><nav className={base.categoryStrip} aria-label="Store categories"><Link href={storesHref(params,{category:undefined,page:undefined})} aria-current={!query.category?"page":undefined}><Grid2X2 size={15} aria-hidden/>All stores</Link>{catalog.options.categories.map(c=><Link key={c.value} href={storesHref(params,{category:c.value,page:undefined})} aria-current={query.category===c.value?"page":undefined}>{c.label}<span>{c.count}</span></Link>)}</nav>{chips.length>0&&<div className={base.activeFilters} aria-label="Active filters">{chips.map(chip=><Link key={chip.key} href={storesHref(params,{[chip.key]:undefined,page:undefined})} aria-label={`Remove ${chip.label} filter`}>{chip.label}<X size={13} aria-hidden/></Link>)}<Link href="/stores#store-results" className={base.clearFilters}>Clear all</Link></div>}
    <StoresBrowser key={"browser-"+JSON.stringify(query)} query={query} options={catalog.options} total={catalog.total}>{catalog.stores.length?<div className={styles.grid}>{catalog.stores.map((store,i)=><StoreDirectoryCard key={store.id} store={store} index={i} saved={saved.includes(store.id)}/>)}</div>:<div className={base.empty}><Store size={45} strokeWidth={1.3} aria-hidden/><h3>{catalog.inventoryCount?"Your next favourite is out there.":"Something local is growing."}</h3><p>{catalog.inventoryCount?"Try another name or area, or clear a filter to meet more of our local businesses.":"New businesses are making a home on LinkWe. Check back to see what’s new."}</p><Link href="/stores#store-results">Explore all stores</Link></div>}{catalog.total>0&&<div className={base.pagination}><p>Showing {(catalog.page-1)*STORE_PAGE_SIZE+1}–{Math.min(catalog.page*STORE_PAGE_SIZE,catalog.total)} of {catalog.total} {catalog.total===1?"store":"stores"}</p>{catalog.pages>1&&<nav aria-label="Store pages">{catalog.page>1&&<Link href={storesHref(params,{page:String(catalog.page-1)})} aria-label="Previous page"><ArrowLeft size={18} aria-hidden/></Link>}<span>Page {catalog.page} of {catalog.pages}</span>{catalog.page<catalog.pages&&<Link href={storesHref(params,{page:String(catalog.page+1)})} aria-label="Next page"><ArrowRight size={18} aria-hidden/></Link>}</nav>}</div>}</StoresBrowser>
    <StoresMap key={"map-"+JSON.stringify(query)} stores={catalog.matches.map(({id,slug,name,latitude,longitude,region,preview})=>({id,slug,name,latitude,longitude,region,preview}))} preview={catalog.preview}/><div className={styles.trustNotes}><div><Store size={23} strokeWidth={1.5} aria-hidden/><div><strong>Get to know the business</strong><p>Explore their work, their story and the details that matter.</p></div></div><div><Heart size={23} strokeWidth={1.5} aria-hidden/><div><strong>Keep your favourites close</strong><p>Follow a store to find it again whenever you need it.</p></div></div><div><ShieldCheck size={23} strokeWidth={1.5} aria-hidden/><div><strong>Choose with confidence</strong><p>Read customer reviews, policies and contact information.</p></div></div></div></section>
    <section className={`${base.container} ${base.bottomBanner}`}><div><p className={base.eyebrow}>WE PEOPLE. WE BUSINESS.</p><h2>Your passion. <em>Your place on LinkWe.</em></h2><p>Give your business a storefront worth discovering.</p></div><Link href="/register?role=vendor">Open your store <ArrowUpRight size={19} aria-hidden/></Link></section>
  </main></div>;
}
