import Link from "next/link";
import { redirect } from "next/navigation";
import { ShoppingBag, Store, CalendarCheck, ArrowLeft, Check } from "lucide-react";
import { getCurrentUser } from "@/lib/auth/current-user";
import { resolveAuthLandingPath } from "@/lib/auth/landing";
import { parseIntendedPlanParam } from "@/lib/onboarding/intended-plan";
import BusinessButton from "./business-button";
export const metadata = { title: "Your business, your LinkWe | LinkWe" };
export default async function StartBusinessPage({ searchParams }: { searchParams: Promise<{ plan?: string }> }) {
  const [user, sp] = await Promise.all([getCurrentUser(), searchParams]);
  if (user && user.role !== "CUSTOMER") redirect(await resolveAuthLandingPath(user));
  const plan = parseIntendedPlanParam(sp.plan);
  const suffix = plan ? `?plan=${plan.toLowerCase()}` : "";
  return <main className="min-h-dvh bg-[#f0f6fa] px-4 py-8 sm:py-14"><div className="mx-auto max-w-5xl"><Link href={user ? "/dashboard/customer" : "/"} className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-[#174766]"><ArrowLeft size={17}/> {user ? "My Dashboard" : "Back to LinkWe"}</Link><div className="grid overflow-hidden rounded-[32px] border border-sky-100 bg-white shadow-xl shadow-sky-950/5 md:grid-cols-2"><section className="bg-[radial-gradient(circle_at_top_right,#237d94,transparent_65%),linear-gradient(135deg,#13334e,#174766)] p-7 text-white sm:p-10"><Store size={35} className="text-orange-300"/><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-sky-200">LinkWe for business</p><h1 className="mt-3 text-4xl font-black leading-tight">One account.<br/>Your next <span className="text-orange-300">chapter.</span></h1><p className="mt-5 leading-7 text-sky-100">Sell products, offer services or host events. Add a business workspace to the LinkWe account you already use.</p><div className="mt-9 space-y-4">{[[ShoppingBag,"Keep your shopping history and favourites"],[Store,"Give your business a storefront"],[CalendarCheck,"Choose the tools and plan that fit you"]].map(([Icon, text]) => { const I = Icon as typeof Store; return <p key={String(text)} className="flex items-center gap-3 text-sm"><I size={20} className="shrink-0 text-orange-300"/>{String(text)}</p>; })}</div></section><section className="flex flex-col justify-center p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-[#d4450a]">You’re in control</p><h2 className="mt-3 text-2xl font-bold text-[#174766]">Make room for your business.</h2><ol className="my-7 space-y-5">{["Enable your business workspace", "Choose a plan and set up your store", "Switch between shopping and business from the menu"].map((text,index)=><li key={text} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-sky-50 font-bold text-[#174766]">{index+1}</span>{text}</li>)}</ol><p className="mb-6 flex gap-2 rounded-2xl bg-orange-50 p-4 text-sm leading-6 text-orange-900"><Check size={20} className="shrink-0"/>Enabling your workspace doesn’t charge you or publish a store. You’ll review your plan during setup.</p>{user ? <BusinessButton plan={plan ?? undefined}/> : <div className="space-y-3"><Link className="block rounded-2xl bg-[#e85a16] px-5 py-4 text-center font-bold text-white" href={`/register/business${suffix}`}>Create an account</Link><Link className="block py-2 text-center text-sm font-semibold text-[#174766]" href={`/login?callbackUrl=${encodeURIComponent(`/start-business${suffix}`)}`}>Already on LinkWe? Sign in</Link></div>}</section></div></div></main>;
}
