-- AlterTable
ALTER TABLE "event_promo_codes" ADD COLUMN     "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "discountValue" SET DATA TYPE INTEGER;
