"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, Bell, Check, CheckCircle2, Copy, Download, Heart, Monitor, ShoppingBag, Smartphone, Sparkles } from "lucide-react";
import PublicNav from "@/components/layout/PublicNav";
import { toastPWAInstalled } from "@/components/ui/pwa-installed-toast";
import { usePWAInstall } from "@/lib/hooks/use-pwa-install";
import { detectInstallPlatform, INSTALL_GUIDES, type InstallPlatform } from "@/lib/pwa/install";
import styles from "./install.module.css";
export default function GetAppClient({ user = null, dashboardHref }: { user?: { name: string; href: string } | null; dashboardHref?: string }) {
  const [platform, setPlatform] = useState<InstallPlatform>("desktop"), [detected, setDetected] = useState(false), [message, setMessage] = useState(""), [copied, setCopied] = useState(false);
  const guide = useRef<HTMLElement>(null);
  const { isInstalled, isInstallable, isInstalling, error, install } = usePWAInstall({ onInstalled: toastPWAInstalled });
  useEffect(() => { setPlatform(detectInstallPlatform(navigator.userAgent, navigator.maxTouchPoints)); setDetected(true); }, []);
  async function addApp() {
    if (isInstallable) { const accepted = await install(); setMessage(accepted ? "Installation requested. Your browser will finish adding LinkWe." : "You can install whenever you’re ready using the steps below."); }
    else guide.current?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "start" });
  }
  async function copyLink() { try { await navigator.clipboard.writeText(window.location.origin + "/get-app"); setCopied(true); } catch { setMessage("Copy this page’s address from your browser to open it on another device."); } }
  const current = INSTALL_GUIDES[platform];
  return <div className={styles.page}><PublicNav user={user} dashboardHref={dashboardHref}/><main className={styles.main}>
    <section className={styles.hero}><div className={styles.intro}><span className={styles.eyebrow}><Sparkles size={15}/> TAKE LOCAL WITH YOU</span><h1>Your LinkWe.<br/><em>Always close.</em></h1><p>Your favourite stores, services, events and conversations. Give them a home on your phone or computer.</p><div className={styles.actions}>{isInstalled ? <Link href={dashboardHref || "/shop"} className={styles.primary}><CheckCircle2 size={19}/> You’re all set <ArrowRight size={17}/></Link> : <button className={styles.primary} onClick={() => void addApp()} disabled={isInstalling}><Download size={19}/>{isInstalling ? "Opening install prompt…" : isInstallable ? "Install app" : "Add LinkWe to my device"}</button>}<Link href="/shop" className={styles.secondary}>Keep exploring <ArrowRight size={16}/></Link></div><p className={styles.caption}>{isInstalled ? "LinkWe is installed or running as an app on this device." : "No app download fee. Your existing LinkWe account works here."}</p><div role="status" className={styles.status}>{error || message}</div></div>
    <div className={styles.preview} aria-hidden="true"><div className={styles.phone}><div className={styles.notch}/><div className={styles.phoneHead}><img src="/branding/v2/app-192.png" alt=""/><div><strong>LinkWe</strong><span>Your local world.</span></div><Bell size={19}/></div><div className={styles.phoneFeature}><span>ALL LOCAL. ALL YOURS.</span><h2>A little closer.<br/>A lot more local.</h2><ShoppingBag size={38}/></div><div className={styles.phoneGrid}><div><ShoppingBag/><b>Shop</b><span>Find your next favourite</span></div><div><Sparkles/><b>Book</b><span>Make time for you</span></div></div><div className={styles.phoneSaved}><Heart size={20}/><div><b>Your favourites, together.</b><span>Pick up right where you left off.</span></div></div><div className={styles.phoneNav}><ShoppingBag/><Heart/><Bell/></div></div><div className={styles.floatBadge}><CheckCircle2 size={19}/><span>One icon. Your marketplace.</span></div></div></section>
    <section className={styles.setup} ref={guide} id="install-guide"><div><span className={styles.eyebrow}>A FEW SIMPLE STEPS</span><h2>{isInstalled ? "Ready when you are." : current.title}</h2><p>{detected ? "We’ve selected a guide for this device. You can choose another below." : "Choose your device to see the right steps."}</p></div><div className={styles.platforms} aria-label="Installation guides">{(Object.entries(INSTALL_GUIDES) as [InstallPlatform, typeof current][]).map(([key, value]) => <button key={key} aria-pressed={platform === key} onClick={() => setPlatform(key)}>{key === "ios" || key === "android" ? <Smartphone size={17}/> : <Monitor size={17}/>} {value.label}</button>)}</div><ol className={styles.steps}>{current.steps.map((step, i) => <li key={step}><span>{i + 1}</span><p>{step}</p></li>)}</ol><div className={styles.note}><p>{current.note}</p><button onClick={() => void copyLink()}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? "Link copied" : "Copy app link"}</button></div></section>
    <section className={styles.benefits}>{[{Icon:ShoppingBag,title:"Everything in one place",text:"Shop, book services and discover events with your existing account."},{Icon:Heart,title:"Your favourites stay with you",text:"Keep your saved products and stores close, wherever you open LinkWe."},{Icon:Bell,title:"Stay in the loop",text:"Read your updates in Notifications. Device alerts are always your choice."}].map(({Icon,title,text})=><article key={title}><Icon size={23}/><h3>{title}</h3><p>{text}</p></article>)}</section>
    <div className={styles.faq}><h2>A few things to know.</h2><details><summary>Will I need to sign up again?</summary><p>No. Sign in with the LinkWe account you already use. Your orders, saved items and messages stay connected to that account.</p></details><details><summary>Why don’t I see an install button?</summary><p>The option depends on your browser, device and whether the app is already installed. Use the guide above or open this page in a supported browser outside social media and embedded app previews.</p></details><details><summary>Does the app work without internet?</summary><p>An internet connection is needed for shopping, current prices, bookings, payments and messages. LinkWe shows an offline page if your connection drops.</p></details></div>
  </main></div>;
}
