"use client";
import { useId, useState } from "react";
import { Check, ChevronDown, Search } from "lucide-react";

export default function SearchableSelect({ label, value, options, onChange, disabled, placeholder = "Choose an option", clearLabel = "Not set" }: { label: string; value: string; options: { value: string; label: string; detail?: string }[]; onChange: (value: string) => void; disabled?: boolean; placeholder?: string; clearLabel?: string }) {
  const id = useId(), [open, setOpen] = useState(false), [query, setQuery] = useState("");
  const choice = options.find(option => option.value === value);
  const shown = options.filter(option => `${option.label} ${option.detail || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="relative min-w-0" onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget)) setOpen(false); }} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); event.stopPropagation(); } }}>
    <button type="button" className="admin-input flex items-center justify-between gap-2 text-left" aria-label={label} aria-expanded={open} aria-controls={`${id}-choices`} disabled={disabled} onClick={() => { setOpen(!open); setQuery(""); }}><span className="min-w-0 truncate">{choice?.label || value || placeholder}</span><ChevronDown size={15} className="shrink-0"/></button>
    {open && <div id={`${id}-choices`} className="absolute inset-x-0 top-full z-40 mt-1 rounded-xl border border-[#d9e4da] bg-white p-2 shadow-xl"><label className="flex items-center gap-2 border-b border-zinc-100 px-2"><Search size={14}/><input autoFocus aria-label={`Search ${label.toLowerCase()}`} className="min-h-10 min-w-0 flex-1 bg-transparent text-xs outline-none" value={query} placeholder="Type to find…" onChange={event => setQuery(event.target.value)}/></label><div className="max-h-52 overflow-auto" role="group" aria-label={`${label} choices`}><button type="button" className="flex min-h-10 w-full items-center rounded-md px-2 text-left text-xs text-zinc-500 hover:bg-[#f0f5ed]" onClick={() => { onChange(""); setOpen(false); }}>{clearLabel}</button>{shown.slice(0, 100).map(option => <button type="button" key={option.value} className="flex min-h-11 w-full items-center gap-2 rounded-md px-2 py-2 text-left text-xs hover:bg-[#f0f5ed]" aria-pressed={value === option.value} onClick={() => { onChange(option.value); setOpen(false); }}><span className="min-w-0 flex-1"><span className="block break-words">{option.label}</span>{option.detail && <small className="mt-1 block text-zinc-500">{option.detail}</small>}</span>{value === option.value && <Check size={14}/>}</button>)}{!shown.length && <p className="px-2 py-3 text-xs text-zinc-500">No matches. Try another name.</p>}{shown.length > 100 && <p className="px-2 py-2 text-xs text-zinc-500">Type more to narrow down {shown.length} matches.</p>}</div></div>}
  </div>;
}
