"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import { humanLabel } from "@/lib/admin/record-design";

// A form for additional attributes, including nested data, without requiring JSON editing.
export default function StructuredFields({ value, onChange, label = "Additional details", depth = 0 }: { value: unknown; onChange: (value: unknown) => void; label?: string; depth?: number }) {
  const [name, setName] = useState(""), [type, setType] = useState("text");
  const defaults: Record<string, unknown> = { text: "", number: 0, boolean: false, object: {}, list: [] };
  const blocked = ["__proto__", "prototype", "constructor"];
  if (depth > 8) return <p className="admin-field-help">This detail has many nested levels. Ask Rex to help edit it.</p>;
  if (Array.isArray(value)) return <div className="space-y-3">{value.map((item, index) => <div key={index} className="rounded-lg border border-zinc-200 p-3"><div className="mb-2 flex items-center justify-between gap-2"><strong className="text-xs">{label} {index + 1}</strong><button type="button" className="admin-icon-button" aria-label={`Remove ${label} ${index + 1}`} onClick={() => onChange(value.filter((_, i) => i !== index))}><X size={14}/></button></div><StructuredFields value={item} label={`${label} ${index + 1}`} depth={depth + 1} onChange={next => onChange(value.map((existing, i) => i === index ? next : existing))}/></div>)}<div className="admin-inline-fields"><select className="admin-input" aria-label={`Type of new ${label.toLowerCase()}`} value={type} onChange={e => setType(e.target.value)}><option value="text">Text item</option><option value="number">Number</option><option value="object">Detailed item</option></select><button type="button" className="admin-button" onClick={() => onChange([...value, defaults[type]])}><Plus size={15}/>Add item</button></div></div>;
  if (value == null || typeof value === "object") {
    const entries = value && typeof value === "object" ? Object.entries(value) : [];
    return <div className="space-y-3">{entries.map(([key, entry]) => <div key={key} className="rounded-lg border border-zinc-200 bg-white p-3"><div className="mb-2 flex items-center justify-between gap-2"><label className="text-xs font-medium">{humanLabel(key)}</label><button type="button" className="admin-icon-button" aria-label={`Remove ${humanLabel(key)}`} onClick={() => onChange(Object.fromEntries(entries.filter(([name]) => name !== key)))}><X size={13}/></button></div><StructuredFields value={entry ?? ""} depth={depth + 1} label={humanLabel(key)} onChange={next => onChange({ ...(value as object), [key]: next })}/></div>)}<div className="flex flex-wrap gap-2"><input aria-label={`New ${label.toLowerCase()} name`} className="admin-input min-w-32 flex-1" placeholder="Detail name, e.g. colour" value={name} onChange={e => setName(e.target.value)}/><select className="admin-input w-auto" aria-label={`New ${label.toLowerCase()} type`} value={type} onChange={e => setType(e.target.value)}><option value="text">Text</option><option value="number">Number</option><option value="boolean">Yes / no</option><option value="object">Group of details</option><option value="list">List</option></select><button type="button" className="admin-button" disabled={!name.trim() || blocked.includes(name.trim()) || entries.some(([key]) => key === name.trim())} onClick={() => { onChange({ ...(value as object || {}), [name.trim()]: defaults[type] }); setName(""); }}><Plus size={15}/>Add detail</button></div></div>;
  }
  if (typeof value === "boolean") return <label className="flex min-h-10 items-center gap-2 text-xs"><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)}/>{value ? "Yes" : "No"}</label>;
  return <input className="admin-input" aria-label={label} type={typeof value === "number" ? "number" : "text"} step="any" value={String(value ?? "")} onChange={e => onChange(typeof value === "number" && e.target.value !== "" ? Number(e.target.value) : e.target.value)}/>;
}
