"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowDownToLine, ArrowRight, CheckCircle2, Clock3, Package, RefreshCw, Search, Truck, Wallet, X } from "lucide-react";
import { toast } from "sonner";
import { cancelOrders, completeSplitOrder, exportOrdersCSV, getAdminOrderActivity, getAdminOrderWorkspace } from "@/app/actions/admin-orders";
import { ORDER_QUEUES, orderNextStep, orderStatusLabel, type OrderQueue, type OrderFilters } from "@/lib/admin/order-workspace";
import AdminDialog from "./admin-dialog";
import OrderControls from "./order-controls";
import s from "./orders-workspace.module.css";

type Workspace = Awaited<ReturnType<typeof getAdminOrderWorkspace>>;
type Order = Workspace["orders"][number];
const QUEUES: Record<OrderQueue, string> = { all:"All orders", attention:"Needs attention", payment:"Awaiting payment", fulfillment:"In preparation", transit:"On the way", payout:"Earnings to review", closed:"Closed" };
const money = (minor: number) => new Intl.NumberFormat("en-TT", { style:"currency", currency:"TTD" }).format(minor / 100);
const date = (value: Date | string) => new Date(value).toLocaleString("en-TT", { timeZone:"America/Port_of_Spain", dateStyle:"medium", timeStyle:"short" });
const ref = (o: Order) => o.referenceNumber ?? o.id.slice(-8).toUpperCase();
const sandbox = (o: Order) => (o.paymentAttempts[0]?.providerData as {environment?:string} | null)?.environment === "sandbox";
function Badge({status}:{status:string}) { return <span className={s.badge} data-tone={["CANCELLED","REFUNDED","FAILED","ERROR"].includes(status)?"red":["COMPLETED","DELIVERED","SUCCEEDED"].includes(status)?"green":status==="PENDING_PAYMENT"?"amber":"blue"}>{orderStatusLabel(status)}</span>; }

function Detail({order,onRefresh}:{order:Order;onRefresh:()=>void}) {
 const [activity,setActivity]=useState<Awaited<ReturnType<typeof getAdminOrderActivity>>>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;getAdminOrderActivity(order.id).then(v=>{if(current)setActivity(v);}).catch(()=>{if(current)setError("Activity could not load.");});return()=>{current=false;};},[order.id,order.updatedAt]);
 return <div className={s.detail}>
  <div className={s.detailHero}><div><Badge status={order.status}/>{sandbox(order)&&<span className={s.badge}>Test payment</span>}<h3>{money(order.totalMinor)}</h3><p>Placed {date(order.createdAt)}</p></div><Package size={36}/></div>
  <div className={s.next}><ArrowRight size={18}/><div><strong>Next step</strong><p>{orderNextStep(order)}</p></div></div>
  <div className={s.detailGrid}><section><h3>Customer</h3><strong>{order.buyer.fullName}</strong><a href={`mailto:${order.buyer.email}`}>{order.buyer.email}</a><p>{order.region || "Region not supplied"}</p></section><section><h3>Payment</h3><strong>{order.paymentAttempts[0] ? orderStatusLabel(order.paymentAttempts[0].status) : "No payment attempt recorded"}</strong><p>{sandbox(order)?"Sandbox · test transaction":"Check the payment record before fulfillment."}</p></section></div>
  <section><h3>Items · {order.items.reduce((n,i)=>n+i.quantity,0)}</h3>{order.items.length?order.items.map(i=><div className={s.line} key={i.id}><div><strong>{i.titleSnapshot}</strong><p>{i.store.name} · Quantity {i.quantity}</p></div><strong>{money(i.priceMinor*i.quantity)}</strong></div>):<p>No items recorded.</p>}<div className={s.totals}><span>Subtotal</span><strong>{money(order.subtotalMinor)}</strong><span>Shipping</span><strong>{money(order.shippingMinor)}</strong><span>Order total</span><strong>{money(order.totalMinor)}</strong></div></section>
  <section><h3>Vendor parcels · {order.splitOrders.length}</h3>{order.splitOrders.length?order.splitOrders.map(split=><div className={s.parcel} key={split.id}><div className={s.line}><div><strong>{split.store.name}</strong><p>{split.referenceNumber ?? split.id.slice(-8).toUpperCase()}</p></div><Badge status={split.status}/></div><p>{split.bayNumber?`Bay ${split.bayNumber} · `:""}{money(split.subtotalMinor)}{split.earningsReleased?" · Earnings released":""}</p>{split.status==="DELIVERED"&&!split.earningsReleased&&<button disabled={busy} className={s.secondary} onClick={async()=>{if(!window.confirm(`Release earnings for ${split.store.name}? This cannot be undone here.`))return;setBusy(true);try{const r=await completeSplitOrder(split.id);if(!r.ok)throw Error(r.error);toast.success("Vendor earnings released.");onRefresh();}catch(e){toast.error(e instanceof Error?e.message:"Could not release earnings.");}finally{setBusy(false);}}}>Review & release earnings</button>}</div>):<p>Parcels appear after payment and order processing.</p>}</section>
  <OrderControls key={order.id+String(order.updatedAt)} orderId={order.id} status={order.status} splits={order.splitOrders} sandboxPayment={sandbox(order)} hasShippingAddress={!!order.shippingAddressId} onRefresh={onRefresh}/>
  <section><h3>Recent staff activity</h3>{error?<p role="alert">{error}</p>:activity.length?activity.map(a=><article key={a.id} className={s.activity}><strong>{orderStatusLabel(a.action.toUpperCase())}</strong><p>{a.note}</p><small>{a.actor} · {date(a.at)}</small></article>):<p>No staff notes or operational updates recorded.</p>}</section>
 </div>;
}

export default function OrdersTab() {
 const params=useSearchParams();
 const [search,setSearch]=useState(params.get("q")??""),[queue,setQueue]=useState<OrderQueue>("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[sort,setSort]=useState<NonNullable<OrderFilters["sort"]>>("newest"),[page,setPage]=useState(1);
 const [data,setData]=useState<Workspace|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[revision,setRevision]=useState(0),[selected,setSelected]=useState<string[]>([]),[open,setOpen]=useState<Order|null>(null),[cancel,setCancel]=useState(false),[reason,setReason]=useState(""),[busy,setBusy]=useState(false);
 const refresh=()=>setRevision(n=>n+1);
 useEffect(()=>{let current=true;const timer=setTimeout(()=>{setLoading(true);setError("");getAdminOrderWorkspace({search,queue,from,to,sort,limit:25,offset:(page-1)*25}).then(result=>{if(!current)return;setData(result);if(page>Math.max(1,Math.ceil(result.total/25)))setPage(Math.max(1,Math.ceil(result.total/25)));setSelected([]);setOpen(previous=>previous?result.orders.find(o=>o.id===previous.id)??null:null);setLoading(false);}).catch(e=>{if(current){setError(e instanceof Error?e.message:"Could not load orders.");setLoading(false);}});},250);return()=>{current=false;clearTimeout(timer);};},[search,queue,from,to,sort,page,revision]);
 const changeQueue=(value:OrderQueue)=>{setQueue(value);setPage(1);setSelected([]);};
 const reset=()=>{setSearch("");setQueue("all");setFrom("");setTo("");setSort("newest");setPage(1);};
 const orders=data?.orders??[],count=data?.total??0,pages=Math.max(1,Math.ceil(count/25));
 const exportParams=new URLSearchParams({q:search,queue,...(from?{from}:{}),...(to?{to}:{})});
 const exportSelected=async()=>{setBusy(true);try{const csv=await exportOrdersCSV(selected);const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="linkwe-selected-orders.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{toast.error("Could not export selected orders.");}finally{setBusy(false);}};
 return <div className={s.workspace}>
  <header className={s.header}><div><p className={s.eyebrow}>MARKETPLACE OPERATIONS</p><h1>Every order. A clear next step.</h1><p>Follow the journey from checkout to the customer’s door.</p></div><div className={s.actions}><button className={s.secondary} onClick={refresh} disabled={loading}><RefreshCw size={16}/>{loading?"Updating…":"Refresh"}</button><a className={s.primary} href={`/api/admin/orders/export?${exportParams}`}><ArrowDownToLine size={16}/>Export results</a></div></header>
  <section className={s.hero}><div><span className={s.eyebrow}>YOUR ORDER DESK</span><h2>Keep good business moving.</h2><p>See what needs a follow-up, keep parcels moving, and close the loop with your vendors.</p><button onClick={()=>changeQueue("attention")}>Review what needs attention <ArrowRight size={17}/></button></div><div className={s.heroStat}><span>Across the marketplace</span><strong>{data?.counts.all??"—"}</strong><span>customer orders</span></div></section>
  <div className={s.metrics}>{([
   ["attention",Clock3,"No update in 48h or earnings ready"], ["fulfillment",Package,"Vendor preparation & packing"], ["transit",Truck,"Orders on their way"], ["payout",Wallet,"Delivered parcels awaiting release"],
  ] as const).map(([key,Icon,description])=><button className={s.metric} data-active={queue===key} key={key} onClick={()=>changeQueue(key)}><span className={s.metricIcon}><Icon size={19}/></span><span>{QUEUES[key]}</span><strong>{data?.counts[key]??"—"}</strong><small>{description}</small></button>)}</div>
  <section className={s.panel}>
   <nav className={s.queues} aria-label="Order queues">{ORDER_QUEUES.map(key=><button key={key} aria-pressed={queue===key} onClick={()=>changeQueue(key)}>{QUEUES[key]}<span>{data?.counts[key]??"—"}</span></button>)}</nav>
   <div className={s.filters}><label className={s.search}><Search size={18}/><input aria-label="Search orders" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);setSelected([]);}} placeholder="Search order, customer, item or vendor…"/></label><label>From<input aria-label="Orders from date" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>To<input aria-label="Orders to date" type="date" value={to} min={from} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><label>Sort<select value={sort} onChange={e=>{setSort(e.target.value as typeof sort);setPage(1);}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="value">Highest value</option></select></label></div>
   <div className={s.results}><p><strong>{count}</strong> matching orders · All amounts in TTD</p>{(search||from||to||queue!=="all")&&<button onClick={reset}>Clear filters <X size={13}/></button>}</div>
   {selected.length>0&&<div className={s.selection}><strong>{selected.length} selected on this page</strong><button disabled={busy||loading} onClick={()=>void exportSelected()}>Export selected</button><button disabled={busy||loading} onClick={()=>setCancel(true)}>Cancel selected…</button><button onClick={()=>setSelected([])}>Clear</button></div>}
   {error?<div className={s.empty} role="alert"><h3>Orders couldn’t load</h3><p>{error}</p><button className={s.secondary} onClick={refresh}>Try again</button></div>:loading?<div className={s.empty} role="status"><RefreshCw size={25}/><p>Loading your order desk…</p></div>:!orders.length?<div className={s.empty}><CheckCircle2 size={34}/><h3>{queue==="attention"?"Nothing needs attention here":"No orders match these filters"}</h3><p>Try another queue or clear your search.</p><button className={s.secondary} onClick={reset}>Show all orders</button></div>:<div className={s.tableWrap}><table className={s.table}><thead><tr><th><input type="checkbox" aria-label="Select all orders on this page" checked={orders.length>0&&selected.length===orders.length} onChange={e=>setSelected(e.target.checked?orders.map(o=>o.id):[])}/></th><th>Order & customer</th><th>Status</th><th>Vendor progress</th><th>Total</th><th>Next step</th><th/></tr></thead><tbody>{orders.map(o=>{const done=o.splitOrders.filter(p=>["DELIVERED","COMPLETED"].includes(p.status)).length;return <tr key={o.id}><td><input type="checkbox" aria-label={`Select ${ref(o)}`} checked={selected.includes(o.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,o.id]:ids.filter(id=>id!==o.id))}/></td><td><button className={s.orderLink} onClick={()=>setOpen(o)}>{ref(o)}</button><p>{o.buyer.fullName}</p><small>{date(o.createdAt)}</small></td><td><Badge status={o.status}/>{sandbox(o)&&<small>Test payment</small>}</td><td><strong>{o.splitOrders.length?`${done} of ${o.splitOrders.length} delivered`:"Awaiting processing"}</strong><p>{o.items.reduce((n,i)=>n+i.quantity,0)} items · {o.region||"No region"}</p>{o.splitOrders.length>0&&<div className={s.progress}><span style={{width:`${done/o.splitOrders.length*100}%`}}/></div>}</td><td className={s.amount}>{money(o.totalMinor)}</td><td><span className={s.nextLabel}>{orderNextStep(o)}</span></td><td><button className={s.openButton} aria-label={`Open order ${ref(o)}`} onClick={()=>setOpen(o)}><ArrowRight size={18}/></button></td></tr>;})}</tbody></table></div>}
   <footer className={s.pagination}><span>Page {page} of {pages} · {count?Math.min((page-1)*25+1,count):0}–{Math.min(page*25,count)} of {count}</span><div><button disabled={page===1||loading} onClick={()=>{setPage(p=>p-1);setSelected([]);}}>Previous</button><button disabled={page>=pages||loading} onClick={()=>{setPage(p=>p+1);setSelected([]);}}>Next</button></div></footer>
  </section>
  <p className={s.footnote}>Summary cards cover all orders. Search and dates narrow the list and export. Times shown in Trinidad & Tobago.</p>
  {open&&<AdminDialog title={`Order ${ref(open)}`} drawer className={s.orderDrawer} onClose={()=>setOpen(null)}><Detail order={open} onRefresh={refresh}/></AdminDialog>}
  {cancel&&<AdminDialog title={`Cancel ${selected.length} selected orders?`} onClose={()=>{if(!busy)setCancel(false);}}><form className={s.detail} onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await cancelOrders(selected,reason);toast.success(`${result.cancelled} cancelled; ${result.skipped} skipped because their status does not allow cancellation.`);setCancel(false);setReason("");refresh();}catch(e){toast.error(e instanceof Error?e.message:"Could not cancel orders.");}finally{setBusy(false);}}}><p>Only eligible orders will be cancelled. Dispatched, delivered and completed orders are protected. Refunds must be handled separately.</p><label>Reason<textarea required maxLength={2000} rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={s.primary} disabled={busy||!reason.trim()}>{busy?"Cancelling…":"Confirm cancellation"}</button></form></AdminDialog>}
 </div>;
}
