"use client";
import { useCallback, useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { ArrowRight, Box, CheckCircle2, Copy, ExternalLink, MapPin, PackageCheck, RefreshCw, Search, Truck, Warehouse, X } from "lucide-react";
import { toast } from "sonner";
import { getOperationsWorkspace, updateWarehouseOrder, type OperationsWorkspace } from "@/app/actions/admin-operations";
import OperationsAssistant from "./operations-assistant";

const OperationsMap = dynamic(() => import("./warehouse-map"), { ssr: false, loading: () => <div className="h-96 animate-pulse rounded-2xl bg-zinc-100"/> });
type Order = OperationsWorkspace["orders"][number];
const stages = ["All orders", "Collections", "Receiving", "Assembly", "Dispatch", "On the way"] as const;
function physical(o: Order) { return o.splitOrders.filter((s) => o.items.some((i) => i.storeId === s.store.id && !i.product?.isDigital)); }
function stage(o: Order) {
  const splits = physical(o);
  if (splits.length && splits.every((s) => ["DELIVERED", "COMPLETED"].includes(s.status))) return "Delivered";
  if (splits.some((s) => s.status === "READY_FOR_CUSTOMER_PICKUP")) return "Ready for customer pickup";
  if (splits.some((s) => s.status === "OUT_FOR_DELIVERY")) return "On the way";
  if (splits.length && splits.every((s) => s.status === "PACKAGED")) return "Dispatch";
  if (splits.length && splits.every((s) => s.status === "AT_WAREHOUSE")) return "Assembly";
  if (splits.some((s) => s.status === "AWAITING_COURIER_PICKUP")) return "Collections";
  return "Receiving";
}
const refLabel = (o: Order) => o.referenceNumber ?? o.id.slice(-8).toUpperCase();
const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 py-2 text-sm font-medium text-zinc-700 transition hover:bg-zinc-50 disabled:opacity-40";

export default function WarehouseWorkspace() {
  const [data, setData] = useState<OperationsWorkspace | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<string>("All orders");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [view, setView] = useState<"queue" | "map" | "assistant">("queue");
  const [busy, setBusy] = useState(false);
  const [reference, setReference] = useState("");
  const [note, setNote] = useState("");
  const [bay, setBay] = useState("");
  const [warehouseId, setWarehouseId] = useState("");
  const load = useCallback(async () => { try { const result = await getOperationsWorkspace(); setData(result); setError(""); } catch { setError("Could not load operations. Please retry."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); const timer = setInterval(() => { if (!document.hidden) void load(); }, 30_000); return () => clearInterval(timer); }, [load]);
  useEffect(() => { if (!selectedId) return; const close = (e: KeyboardEvent) => { if (e.key === "Escape") setSelectedId(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [selectedId]);
  const selected = data?.orders.find((o) => o.id === selectedId);
  const orders = data?.orders.filter((o) => (filter === "All orders" || stage(o) === filter) && `${refLabel(o)} ${o.buyer.fullName} ${o.region} ${o.splitOrders.map((s) => s.store.name).join(" ")}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  async function act(action: Parameters<typeof updateWarehouseOrder>[0]["action"], splitId?: string) {
    if (!selected || busy) return;
    setBusy(true);
    try {
      const result = await updateWarehouseOrder({ orderId: selected.id, action, splitId, reference, note, warehouseId: warehouseId || data?.warehouses[0]?.id, bay: bay ? Number(bay) : undefined });
      if (!result.ok) toast.error(result.error); else { toast.success("Operation saved"); setReference(""); setNote(""); await load(); }
    } catch { toast.error("Could not save. Refresh and try again."); } finally { setBusy(false); }
  }
  async function copyBooking(o: Order, split?: Order["splitOrders"][number]) {
    const warehouse = data?.warehouses.find((w) => w.id === warehouseId) ?? data?.warehouses[0];
    const items = o.items.filter((i) => !i.product?.isDigital && (!split || i.storeId === split.store.id));
    const addr = o.shippingAddress;
    const text = [
      `LinkWe ${split ? "vendor collection" : "combined customer delivery"} · ${refLabel(o)}`,
      `Pickup: ${split ? `${split.store.name}, ${split.store.address ?? "ADDRESS REQUIRED"}, ${split.store.region ?? ""}` : `${warehouse?.name ?? "WAREHOUSE REQUIRED"}, ${warehouse?.address?.line1 ?? "ADDRESS REQUIRED"}, ${warehouse?.address?.city ?? ""}`}`,
      `Pickup phone: ${split ? split.store.owner.phone ?? "PHONE REQUIRED" : warehouse?.address?.phone ?? "PHONE REQUIRED"}`,
      `Recipient: ${split ? warehouse?.name ?? "LinkWe warehouse" : o.buyer.fullName ?? "NAME REQUIRED"}`,
      `Recipient email: ${split ? "Confirm warehouse email in CSF" : o.buyer.email}`,
      `Recipient phone: ${split ? warehouse?.address?.phone ?? "PHONE REQUIRED" : addr?.phone ?? "PHONE REQUIRED"}`,
      `Delivery address: ${split ? `${warehouse?.address?.line1 ?? "ADDRESS REQUIRED"}, ${warehouse?.address?.city ?? ""}` : `${addr?.line1 ?? "ADDRESS REQUIRED"}, ${addr?.line2 ?? ""}, ${addr?.city ?? ""}`}`,
      `Items: ${items.map((i) => `${i.quantity} × ${i.titleSnapshot}`).join("; ")}`,
      `Estimated weight: ${items.reduce((n, i) => n + i.weightLbs * i.quantity, 0).toFixed(2)} lbs — weigh packed parcel before booking`,
      `Declared merchandise value: TTD ${(items.reduce((n, i) => n + i.priceMinor * i.quantity, 0) / 100).toFixed(2)}`,
      "Collect payment from recipient: NO — already paid through LinkWe",
      `Instructions: ${split ? "Deliver to LinkWe warehouse for consolidation. Do not deliver to the end customer." : "Deliver the complete combined customer order."}`,
    ].join("\n");
    try { await navigator.clipboard.writeText(text); toast.success("Booking details copied. Review and enter them in CSF."); } catch { toast.error("Clipboard unavailable. Use the displayed addresses and order details."); }
  }
  if (loading) return <div className="space-y-5"><div className="h-40 animate-pulse rounded-3xl bg-zinc-200"/><div className="h-96 animate-pulse rounded-3xl bg-zinc-100"/></div>;
  if (!data) return <div role="alert" className="rounded-2xl border bg-white p-8">{error}<button onClick={() => void load()} className={`${button} ml-3`}>Retry</button></div>;
  return <div className="space-y-6">
    <header className="relative overflow-hidden rounded-3xl bg-[#172b2a] p-6 text-white sm:p-8">
      <div className="pointer-events-none absolute -right-16 -top-24 h-80 w-80 rounded-full border-[45px] border-white/5"/>
      <div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-emerald-300">LinkWe / fulfilment centre</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Many stores. One delivery.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/60">Bring every vendor order together. Receive, combine and send it on its way with CSF Couriers.</p></div><a href="https://csfcouriers.com/merchants/" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-[#172b2a]">Open CSF portal <ExternalLink size={16}/></a></div>
      <div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ label: "To collect", count: data.orders.filter((o) => stage(o) === "Collections").length, icon: Truck }, { label: "Ready to combine", count: data.orders.filter((o) => stage(o) === "Assembly").length, icon: Box }, { label: "Ready to dispatch", count: data.orders.filter((o) => stage(o) === "Dispatch").length, icon: PackageCheck }, { label: "On the way", count: data.orders.filter((o) => stage(o) === "On the way").length, icon: ArrowRight }].map((card) => <button key={card.label} onClick={() => { setView("queue"); setFilter(card.label === "To collect" ? "Collections" : card.label === "Ready to combine" ? "Assembly" : card.label === "Ready to dispatch" ? "Dispatch" : "On the way"); }} className="rounded-2xl bg-white/[0.07] p-4 text-left transition hover:bg-white/10"><card.icon size={17} className="mb-3 text-emerald-300"/><p className="text-3xl font-semibold">{card.count}</p><p className="mt-1 text-xs text-white/55">{card.label}</p></button>)}</div>
    </header>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error} Showing the last loaded queue.</p>}
    {!data.warehouses.some((w) => w.address) && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Warehouse address needs setup before packing and CSF handovers. <a href="/dashboard/admin/settings" className="font-semibold underline">Open settings</a>.</div>}
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-zinc-200 bg-white p-1">{(["queue", "map", "assistant"] as const).map((v) => <button key={v} onClick={() => setView(v)} className={`min-h-10 rounded-lg px-4 text-sm font-semibold ${view === v ? "bg-zinc-900 text-white" : "text-zinc-500"}`}>{v === "queue" ? "Work queue" : v === "map" ? "Order map" : "AI assistant"}</button>)}</div><button onClick={() => void load()} className="flex min-h-10 items-center gap-2 text-xs text-zinc-500"><RefreshCw size={14}/> Updated {new Date(data.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</button></div>
    {view === "assistant" ? <OperationsAssistant/> : view === "map" ? <OperationsMap data={data}/> : <section className="overflow-hidden rounded-2xl border border-zinc-200 bg-white">
      <div className="border-b border-zinc-100 p-4 sm:p-5"><div className="flex items-center gap-2 rounded-xl bg-zinc-50 px-3"><Search size={17} className="text-zinc-400"/><input aria-label="Search orders" placeholder="Search order, customer or vendor…" value={query} onChange={(e) => setQuery(e.target.value)} className="min-h-11 min-w-0 flex-1 bg-transparent text-sm outline-none"/></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{stages.map((s) => <button key={s} onClick={() => setFilter(s)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${filter === s ? "bg-orange-50 text-[#D4450A]" : "text-zinc-500 hover:bg-zinc-50"}`}>{s}</button>)}</div></div>
      {!orders.length ? <div className="p-12 text-center"><CheckCircle2 className="mx-auto mb-3 text-emerald-600" size={32}/><h2 className="font-semibold">Queue clear</h2><p className="mt-2 text-sm text-zinc-500">No orders match this view.</p></div> : <div className="divide-y divide-zinc-100">{orders.map((o) => { const splits = physical(o); const received = splits.filter((s) => s.warehouseReceivedAt).length; return <button key={o.id} onClick={() => { setSelectedId(o.id); setReference(""); setNote(""); setBay(""); }} className="group flex w-full flex-col gap-4 p-5 text-left transition hover:bg-zinc-50 sm:flex-row sm:items-center"><span className="hidden rounded-xl bg-orange-50 p-3 text-orange-700 sm:block"><Warehouse size={21}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-zinc-900">{refLabel(o)}</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">{stage(o)}</span></div><p className="mt-1 truncate text-sm text-zinc-500">{o.buyer.fullName ?? "Customer"} · {o.region}</p><p className="mt-2 text-xs text-zinc-400">{splits.map((s) => s.store.name).join(" + ")}</p></div><div className="flex items-center justify-between gap-6 sm:justify-end"><div className="w-32"><p className="mb-2 text-xs text-zinc-500">{received} of {splits.length} parcels received</p><div className="h-1.5 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${splits.length ? received / splits.length * 100 : 0}%` }}/></div></div><ArrowRight size={18} className="text-zinc-400 group-hover:text-orange-700"/></div></button>; })}</div>}
      <p className="border-t border-zinc-100 px-5 py-3 text-[11px] text-zinc-400">Oldest 150 active orders · Refreshes every 30 seconds · Customer shipping is charged once across stores.</p>
    </section>}
    <details className="rounded-2xl border border-zinc-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold">CSF booking guide</summary><div className="mt-4 space-y-3 text-sm leading-6 text-zinc-600"><p>1. Add each vendor under collection points. Save LinkWe warehouse as the delivery recipient for inbound collections.</p><p>2. Add the final customer under Customers. For outbound orders choose LinkWe warehouse as the pickup point.</p><p>3. Add Request Order, enter parcel description, actual packed weight, value and instructions. Select no payment collection for prepaid LinkWe orders.</p><p>4. Review and check out the CSF cart, print the label, then record the CSF reference here. Update delivery using CSF confirmation.</p><p>The published guide is dated October 2020. Verify today’s form and parcel limits in your account; published CSF pages disagree on 50 versus 60 lb limits.</p><a href="https://www.csfcouriers.com/wp-content/uploads/2024/01/how-to-guide_-_merchant_user_guide.pdf" target="_blank" rel="noreferrer" className="text-orange-700 underline">Open CSF’s merchant guide</a></div></details>
    {selected && <div className="fixed inset-0 z-[1300] bg-black/45 backdrop-blur-sm" onClick={() => setSelectedId(null)}><section role="dialog" aria-modal="true" aria-label={`Manage ${refLabel(selected)}`} onClick={(e) => e.stopPropagation()} className="absolute inset-y-0 right-0 w-full max-w-2xl overflow-y-auto bg-[#f7f8f7] pb-12 shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-zinc-200 bg-white px-5 py-4"><div><p className="text-xs font-medium text-zinc-400">CUSTOMER ORDER</p><h2 className="text-xl font-semibold">{refLabel(selected)}</h2></div><button autoFocus aria-label="Close order" onClick={() => setSelectedId(null)} className={button}><X size={18}/></button></header><div className="space-y-5 p-5">
      <div className="rounded-2xl bg-white p-5"><h3 className="font-semibold">{selected.buyer.fullName}</h3><p className="mt-2 text-sm text-zinc-500">{selected.shippingAddress ? `${selected.shippingAddress.line1}, ${selected.shippingAddress.line2 ?? ""} ${selected.shippingAddress.city}` : "Customer pickup — coordinate warehouse collection"}</p><p className="mt-1 text-sm text-zinc-500">{selected.shippingAddress?.phone}</p><p className="mt-3 text-xs text-zinc-400">Combined shipping paid: TTD {(selected.shippingMinor / 100).toFixed(2)}</p></div>
      <div className="space-y-3"><h3 className="font-semibold">Vendor parcels</h3>{physical(selected).map((s) => <article key={s.id} className="rounded-2xl border border-zinc-200 bg-white p-4"><div className="flex justify-between gap-2"><h4 className="font-semibold">{s.store.name}</h4><span className="text-xs text-zinc-500">{s.warehouseReceivedAt ? "Received ✓" : "Awaiting receipt"}</span></div><p className="mt-1 text-xs text-zinc-500">{s.referenceNumber ?? s.id} · {s.status.replaceAll("_", " ")}</p><p className="mt-3 text-sm text-zinc-500">{s.store.address ?? "Vendor address missing"} · {s.store.owner.phone ?? "Phone missing"}</p><p className="mt-2 text-xs font-medium text-orange-700">{s.vendorInboundMethod === "PICKUP_REQUESTED" ? "CSF collection · TTD 40 deducted from earnings" : s.vendorInboundMethod ? "Vendor drop-off · Free" : "Vendor must choose handover method"}</p>{s.inboundShipment?.trackingNumber && <p className="mt-2 text-sm">CSF: {s.inboundShipment.trackingNumber}</p>}<ul className="my-3 text-sm text-zinc-600">{selected.items.filter((i) => i.storeId === s.store.id).map((i, n) => <li key={n}>{i.quantity} × {i.titleSnapshot}</li>)}</ul><div className="flex flex-wrap gap-2">{s.vendorInboundMethod === "PICKUP_REQUESTED" && <button className={button} onClick={() => void copyBooking(selected, s)}><Copy size={14}/> Copy CSF collection</button>}{s.status === "AWAITING_COURIER_PICKUP" && <button disabled={busy || !reference.trim()} className={button} onClick={() => void act("book_collection", s.id)}>Save booking reference</button>}{["VENDOR_PREPARING", "AWAITING_COURIER_PICKUP", "COURIER_ASSIGNED", "COURIER_PICKED_UP", "VENDOR_DROPPED_OFF", "READY_FOR_LINKWE"].includes(s.status) && <button disabled={busy} className={button} onClick={() => void act("receive", s.id)}><PackageCheck size={15}/> Confirm received</button>}</div></article>)}</div>
      <section className="space-y-3 rounded-2xl border border-zinc-200 bg-white p-5"><h3 className="font-semibold">Warehouse controls</h3><label className="block text-xs font-medium">Warehouse<select value={warehouseId || data.warehouses[0]?.id || ""} onChange={(e) => setWarehouseId(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 px-3">{data.warehouses.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="block text-xs font-medium">CSF reference<input value={reference} maxLength={120} onChange={(e) => setReference(e.target.value)} placeholder="Paste the reference after booking in CSF" className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 px-3 text-sm"/></label><label className="block text-xs font-medium">Shelf / bay number (optional)<input type="number" min={1} max={9999} value={bay} onChange={(e) => setBay(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 px-3 text-sm"/></label><label className="block text-xs font-medium">Staff note / delivery evidence<textarea maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-zinc-200 p-3 text-sm"/></label><div className="flex flex-wrap gap-2"><button disabled={busy || !note.trim()} className={button} onClick={() => void act("note")}>Save note</button>{stage(selected) === "Assembly" && <button disabled={busy} className={button} onClick={() => void act("pack")}>Confirm combined & packed</button>}{stage(selected) === "Dispatch" && !selected.shippingAddress && <button disabled={busy} className={button} onClick={() => void act("pickup_ready")}>Notify customer: ready for warehouse pickup</button>}{stage(selected) === "Dispatch" && selected.shippingAddress && <><button className={button} onClick={() => void copyBooking(selected)}><Copy size={14}/> Copy CSF delivery</button><button disabled={busy || !reference.trim()} className={button} onClick={() => void act("dispatch")}><Truck size={15}/> Confirm CSF dispatch</button></>}{stage(selected) === "On the way" && <button disabled={busy || !note.trim()} className={button} onClick={() => void act("deliver")}>Confirm delivered</button>}</div></section>
      {selected.shippingBundles.map((b) => b.shipment && <div key={b.id} className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">Outbound CSF reference: <strong>{b.shipment.trackingNumber}</strong></div>)}
      <section><h3 className="mb-3 font-semibold">Activity history</h3>{selected.documents.map((d) => { const m = d.metadata as { kind?: string; actorName?: string; action?: string; note?: string; reference?: string }; return m?.kind === "warehouse_audit" ? <div key={d.id} className="mb-2 rounded-xl bg-white p-3 text-sm"><p className="font-medium">{m.action?.replaceAll("_", " ")} · {m.actorName}</p><p className="mt-1 text-zinc-500">{m.note || m.reference}</p><p className="mt-1 text-xs text-zinc-400">{new Date(d.generatedAt).toLocaleString()}</p></div> : null; })}</section>
    </div></section></div>}
  </div>;
}
