"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { saveAdminEditableRecord } from "@/app/actions/admin-records";
import type { RecordKind } from "@/lib/admin/record-fields";
type Field = { name: string; type: string; required: boolean; list: boolean; options?: string[]; value: unknown };
export default function RecordEditor({ kind, id, fields }: { kind: RecordKind; id: string; fields: Field[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false);
  const [values, setValues] = useState<Record<string, unknown>>(Object.fromEntries(fields.map((f) => [f.name, f.list ? (Array.isArray(f.value) ? f.value.join("\n") : "") : f.type === "Json" ? JSON.stringify(f.value ?? {}, null, 2) : f.value ?? ""])));
  const input = "mt-2 min-h-11 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm font-normal outline-none focus:border-orange-400";
  return <div className="mx-auto max-w-4xl p-4 sm:p-8"><button onClick={() => router.back()} className="mb-4 min-h-10 text-sm text-zinc-500">← Back</button><h1 className="text-3xl font-semibold capitalize">Edit {kind}</h1><p className="mt-2 break-all text-xs text-zinc-400">{id}</p><form onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { const payload = Object.fromEntries(fields.map((f) => [f.name, f.list ? String(values[f.name]).split("\n").map((s) => s.trim()).filter(Boolean) : f.type === "Json" ? JSON.parse(String(values[f.name])) : values[f.name]])); const result = await saveAdminEditableRecord(kind, id, payload); result.error ? toast.error(result.error) : toast.success("Changes saved"); router.refresh(); } catch { toast.error("Check the structured fields contain valid JSON."); } finally { setBusy(false); } }} className="mt-6 rounded-2xl border border-zinc-200 bg-white p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2">{fields.map((f) => <label key={f.name} className={`block text-xs font-semibold text-zinc-700 ${f.list || f.type === "Json" || /description|policies/i.test(f.name) ? "sm:col-span-2" : ""}`}>{f.name.replace(/([A-Z])/g, " $1")}{f.required ? " *" : ""}{f.list ? " (one per line)" : ""}{f.type === "Boolean" ? <input type="checkbox" checked={!!values[f.name]} onChange={(e) => setValues({ ...values, [f.name]: e.target.checked })} className="ml-3 h-5 w-5 align-middle accent-orange-600"/> : f.options ? <select className={input} value={String(values[f.name])} onChange={(e) => setValues({ ...values, [f.name]: e.target.value })}>{f.options.map((v) => <option key={v}>{v}</option>)}</select> : f.list || f.type === "Json" || /description|policies/i.test(f.name) ? <textarea className={input} rows={5} value={String(values[f.name])} onChange={(e) => setValues({ ...values, [f.name]: e.target.value })}/> : <input className={input} required={f.required} type={["Int", "Float", "Decimal"].includes(f.type) ? "number" : f.name === "email" ? "email" : "text"} step={f.type === "Int" ? 1 : "any"} value={String(values[f.name])} onChange={(e) => setValues({ ...values, [f.name]: e.target.value })}/>}</label>)}</div><p className="mt-5 text-xs text-zinc-400">Changes apply immediately. Verification, payouts and warehouse transitions use their dedicated controls.</p><button disabled={busy} className="mt-4 min-h-12 rounded-xl bg-[#D4450A] px-6 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : "Save changes"}</button></form></div>;
}
