export const featureGroups = [
  { id: "shop", label: "Shop & discover", intro: "Find something good. Keep it all together.", features: [
    { title: "Local marketplace", text: "Browse physical and digital products, variants, categories and stores across Trinidad & Tobago.", href: "/shop" },
    { title: "Services for real life", text: "Discover bookable appointments, custom quotes, on-demand work, virtual services and recurring offers.", href: "/services" },
    { title: "Events & QR tickets", text: "Find your next experience, buy tickets and keep your entry QR in My Tickets. Eligible tickets can be transferred.", href: "/events" },
    { title: "Your customer dashboard", text: "Orders, bookings, tickets, requests, subscriptions, digital purchases and updates in one place.", href: "/dashboard/customer" },
    { title: "One cart, multiple stores", text: "Shop across businesses, apply eligible coupons and review a combined delivery or pickup order before WiPay.", href: "/cart" },
    { title: "Saved favourites", text: "Keep a wishlist, save stores and return to the businesses and items you love.", href: "/wishlist" },
    { title: "Timeline", text: "Discover shoppable posts, photos and updates. Follow, like, comment and share with your community.", href: "/timeline" },
    { title: "Messages & updates", text: "Speak with businesses, follow order progress and receive in-app alerts. Push notifications need your permission.", href: "/messages" },
  ]},
  { id: "business", label: "Run your business", intro: "Your storefront. Your work. Room to grow.", features: [
    { title: "Your own storefront", text: "Bring your business identity, logo, categories, opening hours, location and published listings together.", href: "/register/business" },
    { title: "Guided onboarding", text: "Choose a plan and build a draft store at your pace. Skip ID upload for now and return before launch.", href: "/register/business" },
    { title: "Creation Zone", text: "Create and edit products, services, events, ticket types and coupons from a connected workspace.", href: "/dashboard/vendor/creation" },
    { title: "Products & digital goods", text: "Manage stock, options, variants, images and digital downloads. Ask for order-specific details at checkout.", href: "/dashboard/vendor/products" },
    { title: "Orders & shipping workspace", text: "Prepare vendor portions, track fulfilment and see physical orders needing delivery, pickup or attention.", href: "/dashboard/vendor/shipping" },
    { title: "Service Desk", text: "Keep appointments, quotes, requests and recurring service activity organised with clear next actions.", href: "/dashboard/vendor/service-desk" },
    { title: "Staff & availability", text: "Manage team profiles, service assignments, working hours and time off. Assign appointments to eligible staff.", href: "/dashboard/vendor/staff" },
    { title: "Events & ticket management", text: "Set up event details and ticket types, manage attendees and scan eligible tickets for entry.", href: "/dashboard/vendor/events" },
    { title: "Finance that makes sense", text: "Move between earnings, transactions, payouts, bank details and Plan & Rex. Direct service payments are shown separately.", href: "/dashboard/vendor/finance" },
    { title: "Reviews & replies", text: "See your rating breakdown, filter feedback and respond to customers from the review workspace.", href: "/dashboard/vendor/reviews" },
    { title: "Guided tutorials", text: "Search lessons, track progress, and pause or resume walkthroughs while you learn the workspace.", href: "/dashboard/vendor" },
  ]},
  { id: "grow", label: "Create & grow", intro: "Tools that help your business show up.", features: [
    { title: "Rex, your business assistant", text: "Draft listings, explore store activity and use supported tools for services, coupons, reviews and operations. Review AI work before relying on it.", href: "/dashboard/vendor/ai-assistant" },
    { title: "A clearer Rex allowance", text: "See the percentage of your included allowance remaining, with purchased top-ups shown separately.", href: "/pricing" },
    { title: "Photo Studio", text: "Prepare product imagery with background removal, adjustments and available AI tools. Image allowances and provider limits apply.", href: "/dashboard/vendor/photo-studio" },
    { title: "QR Studio", text: "Create branded QR codes for published LinkWe pages, preview them, choose colours and export PNG, SVG or printable cards.", href: "/dashboard/vendor/qr-studio" },
    { title: "Business collaborations", text: "Request to feature another business’s published listings, review incoming requests and end approved placements. The original seller keeps checkout.", href: "/dashboard/vendor/partners" },
    { title: "Coupons & promotions", text: "Create offers with the available discount, eligibility and redemption controls, and show eligible savings at checkout.", href: "/dashboard/vendor/creation/coupons" },
    { title: "Shoppable Timeline publishing", text: "Connect updates to products, services or events and reach followers. Publishing requires an active Growth or Pro plan.", href: "/pricing" },
    { title: "Visibility controls", text: "Understand store approval, publication and availability requirements before customers can discover or buy from you.", href: "/dashboard/vendor/staff" },
  ]},
  { id: "support", label: "Payments & support", intro: "Clearer steps from first visit to fulfilment.", features: [
    { title: "WiPay card checkout", text: "Review your order on LinkWe, then enter payment details with WiPay. Confirmation returns to your LinkWe account.", href: "/faq" },
    { title: "Delivery, pickup & downloads", text: "See eligible fulfilment choices and a delivery quote before paying. Digital-only orders have no shipping fee.", href: "/shipping-info" },
    { title: "Returns & help", text: "Know how to report an issue, request assistance and follow an approved refund through the payment process.", href: "/returns" },
    { title: "Install LinkWe", text: "Add LinkWe to a supported phone, tablet or desktop for quicker access. Availability depends on your browser.", href: "/get-app" },
    { title: "Privacy & account controls", text: "Read how information is used, control browser permissions and contact the team about your personal data.", href: "/privacy" },
  ]},
];
