"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { MessageSquarePlus, X } from "lucide-react";
import { toast } from "sonner";
import { adminStartConversation } from "@/app/actions/messages";

type Props={people:{id:string;fullName:string;email:string;role:string}[];stores:{id:string;name:string;ownerId:string}[]};
export default function NewMessage({people,stores}:Props){
  const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const router=useRouter();
  const input="mt-1 min-h-11 w-full rounded-xl border border-zinc-200 bg-white px-3 text-sm outline-none focus:border-orange-400";
  return <><button type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#D4450A] px-4 text-sm font-bold text-white"><MessageSquarePlus size={17}/>New message</button>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Start a new message"><form onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);try{const result=await adminStartConversation({customerId:String(fd.get("customerId")),storeId:String(fd.get("storeId")),content:String(fd.get("content"))});if(!result.ok)toast.error(result.error);else router.push(`/dashboard/admin/messages/${result.conversationId}`);}catch{toast.error("Could not start the conversation.");}finally{setBusy(false);}}} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Start a conversation</h2><p className="mt-1 text-sm text-zinc-500">Choose the person and the store context for this message.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close" className="rounded-full p-2 hover:bg-zinc-100"><X size={18}/></button></div><div className="mt-6 space-y-4"><label className="block text-xs font-semibold">Message person<select required name="customerId" className={input}><option value="">Choose a person</option>{people.map(p=><option key={p.id} value={p.id}>{p.fullName} · {p.email} · {p.role}</option>)}</select></label><label className="block text-xs font-semibold">About / through store<select required name="storeId" className={input}><option value="">Choose a store</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block text-xs font-semibold">First message<textarea required name="content" rows={5} maxLength={4000} placeholder="Write as LinkWe Support…" className={`${input} py-3`}/></label></div><p className="mt-3 text-xs leading-5 text-zinc-500">If this person and store already have a conversation, the message is added to that thread. Both sides receive a notification.</p><button disabled={busy} className="mt-5 min-h-11 w-full rounded-xl bg-[#D4450A] font-bold text-white disabled:opacity-50">{busy?"Sending…":"Start conversation"}</button></form></div>}</>;
}
