"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowRight,Bell,CheckCheck,ChevronLeft,ChevronRight,MessageCircle,Package,CalendarDays,Wallet,Star,Search,RefreshCw} from "lucide-react";
import {getNotificationPage,markAllNotificationsRead,markNotificationRead} from "@/app/actions/notifications";
import {NOTIFICATION_LABELS,notificationGroup,safeNotificationHref,type NotificationItem} from "@/lib/notifications/display";
import s from "./notifications.module.css";
const icons={orders:Package,bookings:CalendarDays,messages:MessageCircle,money:Wallet,reviews:Star,updates:Bell};
export function NotificationRow({item,onRead}:{item:NotificationItem;onRead:(item:NotificationItem)=>void}){const group=notificationGroup(item.type),Icon=icons[group as keyof typeof icons];return <button type="button" className={s.row} data-unread={!item.isRead} onClick={()=>onRead(item)}><span className={s.icon}><Icon size={19}/></span><span className={s.copy}><small>{NOTIFICATION_LABELS[group]} · <time dateTime={new Date(item.createdAt).toISOString()}>{new Date(item.createdAt).toLocaleDateString("en-TT",{month:"short",day:"numeric",timeZone:"America/Port_of_Spain"})}</time></small><strong>{item.title}</strong>{item.body&&<span>{item.body}</span>}</span>{!item.isRead&&<i aria-label="Unread"/>}{safeNotificationHref(item.linkUrl)&&<ArrowRight size={15}/>}</button>;}
export default function NotificationCentre(){const [data,setData]=useState<Awaited<ReturnType<typeof getNotificationPage>>|null>(null),[q,setQ]=useState(""),[search,setSearch]=useState(""),[unread,setUnread]=useState(false),[category,setCategory]=useState(""),[page,setPage]=useState(1),[busy,setBusy]=useState(true),[error,setError]=useState("");const seq=useRef(0);
 const load=useCallback(async()=>{const request=++seq.current;setBusy(true);setError("");try{const next=await getNotificationPage({q:search,unread,category,page});if(request===seq.current)setData(next);}catch{if(request===seq.current)setError("We couldn’t load your updates. Please try again.");}finally{if(request===seq.current)setBusy(false);}},[search,unread,category,page]);
 useEffect(()=>{void load();return()=>{seq.current++;};},[load]);
 async function read(item:NotificationItem){try{if(!item.isRead){await markNotificationRead(item.id);window.dispatchEvent(new Event("linkwe-notifications:changed"));}const href=safeNotificationHref(item.linkUrl);if(href)window.location.assign(href);else await load();}catch{setError("Couldn’t update this notification. Please try again.");}}
 async function readAll(){setBusy(true);try{await markAllNotificationsRead(data?.snapshot);window.dispatchEvent(new Event("linkwe-notifications:changed"));await load();}catch{setError("Couldn’t mark your updates as read.");setBusy(false);}}
 return <main className={s.page}><header className={s.hero}><div><span>YOUR LINKWE, UP TO DATE</span><h1>A little update.<br/><em>A clearer day.</em></h1><p>Orders, conversations, bookings and business updates in one place.</p></div><div className={s.heroCount}><Bell size={30}/><strong>{data?.unread??"—"}</strong><span>unread updates</span></div></header><div className={s.layout}><aside><h2>Keep it organised.</h2><p>Choose the updates that matter right now.</p><nav aria-label="Notification categories"><button aria-pressed={!category} onClick={()=>{setCategory("");setPage(1);}}>All updates</button>{Object.entries(NOTIFICATION_LABELS).map(([key,label])=><button key={key} aria-pressed={category===key} onClick={()=>{setCategory(key);setPage(1);}}>{label}</button>)}</nav><Link href="/get-app">Take LinkWe with you <ArrowRight size={15}/></Link></aside><section className={s.content}><div className={s.toolbar}><div className={s.tabs}><button aria-pressed={!unread} onClick={()=>{setUnread(false);setPage(1);}}>All</button><button aria-pressed={unread} onClick={()=>{setUnread(true);setPage(1);}}>Unread</button></div><button onClick={()=>void load()} disabled={busy} aria-label="Refresh notifications"><RefreshCw size={16}/></button><button onClick={()=>void readAll()} disabled={busy||!data?.unread}><CheckCheck size={16}/>Mark all read</button></div><form className={s.search} onSubmit={e=>{e.preventDefault();setSearch(q.trim());setPage(1);}}><Search size={18}/><input type="search" aria-label="Search notifications" value={q} onChange={e=>setQ(e.target.value)} placeholder="Find an order, message or update…"/><button>Search</button></form>{error&&<p role="alert" className={s.error}>{error}<button onClick={()=>void load()}>Try again</button></p>}<div aria-busy={busy}>{!data&&busy?<p className={s.empty}>Loading your updates…</p>:data?.items.length?data.items.map(item=><NotificationRow key={item.id} item={item} onRead={read}/>):<div className={s.empty}><Bell size={34}/><h2>{search||category?"No matching updates.":"You’re all caught up."}</h2><p>{search||category?"Try another search or category.":"Your next update will appear here."}</p></div>}</div>{data&&<footer className={s.pagination}><span>{data.total} updates · Page {data.page} of {data.pages}</span><button aria-label="Previous page" disabled={busy||data.page<=1} onClick={()=>setPage(data.page-1)}><ChevronLeft size={18}/></button><button aria-label="Next page" disabled={busy||data.page>=data.pages} onClick={()=>setPage(data.page+1)}><ChevronRight size={18}/></button></footer>}</section></div></main>;
}
