import Link from "next/link";
import {redirect} from "next/navigation";
import type {ReactNode} from "react";
import {ArrowUpRight,Package,ShoppingBag,CalendarDays,Ticket,MessageCircle,Heart,Bookmark,Repeat2,ClipboardList,Settings,Sparkles,Download,Bell} from "lucide-react";
import {getMyConversations,getUnreadCount as getMessageUnreadCount} from "@/app/actions/messages";
import {getNotifications,getUnreadCount as getNotificationUnreadCount} from "@/app/actions/notifications";
import {getUpcomingTicketsPreview} from "@/app/actions/tickets";
import {getSession} from "@/lib/auth/session";
import {assertDashboardRole} from "@/lib/auth/assert-role";
import {prisma} from "@/lib/prisma";
import {upcomingCustomerBookingsWhere,activeCustomerTicketsWhere,safeAccountHref} from "@/lib/customer/dashboard";
import {paidOrderStatuses,customerOrderState,orderReference,customerDate} from "@/lib/customer/orders";
import {bookingStatus} from "@/lib/customer/experiences";
import {bookingDateLabel} from "@/lib/services/upcoming-bookings";
import {formatEventDateShort,formatEventTime} from "@/lib/events/format-datetime";
import {formatConversationListTime} from "@/lib/messages/format-time";
import type {MainOrderStatus} from "@prisma/client";
import s from "@/components/customer/dashboard.module.css";
function Panel({title,href,label="View all",children,id}:{title:string;href?:string;label?:string;children:ReactNode;id?:string}){return <section className={s.panel} id={id}><header><h2>{title}</h2>{href&&<Link href={href}>{label}<ArrowUpRight size={14}/></Link>}</header>{children}</section>;}
function Empty({text,href,label}:{text:string;href?:string;label?:string}){return <div className={s.empty}><p>{text}</p>{href&&<Link href={href}>{label} <ArrowUpRight size={14}/></Link>}</div>;}
function Thumb({url,children}:{url?:string|null;children:ReactNode}){return <span className={s.thumb}>{url?<img src={url} alt="" loading="lazy"/>:children}</span>;}
const money=(minor:number)=>`TT$${(minor/100).toLocaleString("en-TT",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default async function CustomerDashboardPage(){
 const session=await getSession();if(!session)redirect("/login");assertDashboardRole(session,"CUSTOMER");
 const now=new Date(),upcoming=upcomingCustomerBookingsWhere(session.userId,now);
 const [orders,orderCount,cart,bookings,bookingCount,wishlist,savedStores,savedCount,digitalOrders,conversationsResult,unreadResult,ticketEvents,ticketCount,notifications,notificationCount,requests,requestCount,subscriptions,subscriptionCount]=await Promise.all([
  prisma.mainOrder.findMany({where:{buyerId:session.userId,status:{not:"DRAFT"}},select:{id:true,referenceNumber:true,createdAt:true,status:true,totalMinor:true,shippingAddressId:true,splitOrders:{select:{status:true}},items:{select:{id:true,titleSnapshot:true,quantity:true,store:{select:{name:true,slug:true}},product:{select:{name:true,images:true,isDigital:true}}}}},orderBy:{createdAt:"desc"},take:4}),
  prisma.mainOrder.count({where:{buyerId:session.userId,status:{not:"DRAFT"}}}),
  prisma.productCartItem.aggregate({where:{userId:session.userId},_sum:{quantity:true}}),
  prisma.productBooking.findMany({where:upcoming,select:{id:true,bookingDate:true,startTime:true,endTime:true,status:true,product:{select:{name:true,images:true,store:{select:{name:true}}}}},orderBy:[{bookingDate:"asc"},{startTime:"asc"}],take:3}),
  prisma.productBooking.count({where:upcoming}),
  prisma.wishlist.findUnique({where:{userId:session.userId},select:{_count:{select:{items:true}},items:{take:4,orderBy:{createdAt:"desc"},select:{productId:true,product:{select:{name:true,slug:true,price:true,images:true,isService:true,isPublished:true,isArchived:true}}}}}}),
  prisma.savedStore.findMany({where:{userId:session.userId},take:4,orderBy:{createdAt:"desc"},select:{storeId:true,store:{select:{name:true,slug:true,logoUrl:true}}}}),
  prisma.savedStore.count({where:{userId:session.userId}}),
  prisma.mainOrder.findMany({where:{buyerId:session.userId,status:{in:paidOrderStatuses as MainOrderStatus[]},items:{some:{product:{isDigital:true}}}},select:{id:true,referenceNumber:true,items:{where:{product:{isDigital:true}},select:{titleSnapshot:true}}},orderBy:{createdAt:"desc"},take:3}),
  getMyConversations(),getMessageUnreadCount(),getUpcomingTicketsPreview(session.userId,3),prisma.ticket.count({where:activeCustomerTicketsWhere(session.userId,now)}),getNotifications(),getNotificationUnreadCount(),
  prisma.onDemandRequest.findMany({where:{customerId:session.userId,status:{in:["PENDING","ACCEPTED","CONFIRMED"]}},select:{id:true,status:true,requestType:true,quotedPrice:true,vendorCompletedAt:true,service:{select:{name:true}},store:{select:{name:true}}},orderBy:{updatedAt:"desc"},take:3}),
  prisma.onDemandRequest.count({where:{customerId:session.userId,status:{in:["PENDING","ACCEPTED","CONFIRMED"]}}}),
  prisma.customerServiceSubscription.findMany({where:{customerId:session.userId,status:{in:["ACTIVE","PAUSED","PAST_DUE"]}},select:{id:true,status:true,cancelAtPeriodEnd:true,sessionsRemaining:true,product:{select:{name:true}},store:{select:{name:true}}},orderBy:{updatedAt:"desc"},take:3}),
  prisma.customerServiceSubscription.count({where:{customerId:session.userId,status:{in:["ACTIVE","PAUSED","PAST_DUE"]}}}),
 ]);
 const unread="count"in unreadResult?unreadResult.count:0,conversations=conversationsResult.ok&&conversationsResult.side==="customer"?conversationsResult.conversations.slice(0,3):[];
 const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:"America/Port_of_Spain",hour:"2-digit",hourCycle:"h23"}).format(now));
 const greeting=hour<12?"Good morning":hour<17?"Good afternoon":"Good evening",firstName=session.fullName?.trim().split(/\s+/)[0]||"there";
 const quick=[{label:"My orders",detail:"Track your good finds",value:orderCount,href:"/orders",Icon:Package},{label:"My bookings",detail:"Your next appointment",value:bookingCount,href:"/bookings",Icon:CalendarDays},{label:"My tickets",detail:"Your next good time",value:ticketCount,href:"/my-tickets",Icon:Ticket},{label:"My cart",detail:"Ready when you are",value:cart._sum.quantity??0,href:"/cart",Icon:ShoppingBag}];
 return <div className={`${s.page} pb-mobile-public lg:pb-0`}><div className={s.container}>
  <div className={s.utility}><span>Your LinkWe</span><div><Link href="/messages"><MessageCircle size={16}/>Messages{unread>0&&<b>{unread}</b>}</Link><Link href="/dashboard/customer/settings"><Settings size={16}/>Settings</Link></div></div>
  <header className={s.hero}><div><span className={s.eyebrow}><span/>{greeting}, {firstName}.</span><h1>Your local world.<br/><em>A little closer.</em></h1><p>Good finds, good people and plans to look forward to.<br/>Everything you need, right here.</p><div className={s.heroActions}><Link className={s.primary} href="/shop">Discover something local <ArrowUpRight size={17}/></Link><Link href="/services">Find your next service →</Link></div></div><div className={s.heroArt} aria-hidden><span className={s.orbit}/><div className={s.artCard}><ShoppingBag size={48} strokeWidth={1.2}/><span>A little love<br/>for local.</span><Sparkles size={23}/></div><div className={s.artTicket}><Ticket size={32}/><span>Good times<br/><strong>ahead.</strong></span></div><span className={s.artStar}>✳</span></div></header>
  <nav className={s.quick} aria-label="Your account"><>{quick.map(({label,detail,value,href,Icon})=><Link key={href} href={href}><span className={s.quickIcon}><Icon size={22}/></span><strong>{value}</strong><h2>{label}</h2><p>{detail}</p><ArrowUpRight size={17} className={s.quickArrow}/></Link>)}</></nav>
  {(bookings[0]||ticketEvents[0])&&<Link className={s.next} href={bookings[0]&&(!ticketEvents[0]||new Date(`${bookings[0].bookingDate.toISOString().slice(0,10)}T${bookings[0].startTime}:00-04:00`)<ticketEvents[0].eventStartDate)?`/bookings#booking-${bookings[0].id}`:"/my-tickets"}><CalendarDays size={26}/><div><small>Something to look forward to</small><strong>{bookings[0]&&(!ticketEvents[0]||new Date(`${bookings[0].bookingDate.toISOString().slice(0,10)}T${bookings[0].startTime}:00-04:00`)<ticketEvents[0].eventStartDate)?`${bookings[0].product.name} · ${bookingDateLabel(bookings[0].bookingDate)} at ${bookings[0].startTime}`:`${ticketEvents[0].eventTitle} · ${formatEventDateShort(ticketEvents[0].eventStartDate)}`}</strong></div><ArrowUpRight size={20}/></Link>}
  <div className={s.mainGrid}><div className={s.stack}>
   <Panel title="Your recent finds" href="/orders" id="orders">{orders.length?orders.map(order=>{const state=customerOrderState(order);return <Link className={s.row} key={order.id} href={`/orders/${order.id}`}><Thumb url={order.items[0]?.product?.images[0]}><Package size={24}/></Thumb><div className={s.rowContent}><strong>{order.items[0]?.titleSnapshot??orderReference(order)}</strong><small>{orderReference(order)} · {customerDate(order.createdAt)}</small><span className={s.badge}>{state.label}</span></div><div className={s.rowEnd}><strong>{money(order.totalMinor)}</strong><ArrowUpRight size={17}/></div></Link>;}):<Empty text="Your first local find is waiting." href="/shop" label="Explore the shop"/>}</Panel>
   <Panel title="Your appointments" href="/bookings" id="bookings">{bookings.length?bookings.map(b=><Link href={`/bookings#booking-${b.id}`} className={s.row} key={b.id}><Thumb url={b.product.images[0]}><CalendarDays size={24}/></Thumb><div className={s.rowContent}><strong>{b.product.name}</strong><small>{b.product.store.name} · {bookingDateLabel(b.bookingDate)} at {b.startTime}</small><span className={s.badge}>{bookingStatus(b.status).label}</span></div><ArrowUpRight size={17}/></Link>):<Empty text="Make a little time for yourself. Your upcoming bookings will appear here." href="/services" label="Explore services"/>}</Panel>
   <Panel title="Services in progress" href="/my-requests" label={`${requestCount} open`}><div className={s.sectionLabel}>Requests & quotes</div>{requests.length?requests.map(r=><Link href="/my-requests" className={s.row} key={r.id}><Thumb><ClipboardList size={22}/></Thumb><div className={s.rowContent}><strong>{r.service.name}</strong><small>{r.store.name} · {r.requestType==="QUOTE"?"Quote request":"On-demand request"}</small><span className={s.badge}>{r.status==="ACCEPTED"?"Your response is needed":r.vendorCompletedAt?"Review completed work":r.status==="CONFIRMED"?"Service confirmed":"Waiting for the provider"}</span></div><ArrowUpRight size={17}/></Link>):<Empty text="No open service requests."/>}<Link href="/dashboard/customer/subscriptions" className={s.subLink}><Repeat2 size={18}/><strong>Service subscriptions</strong><span>{subscriptionCount}</span><ArrowUpRight size={16}/></Link>{subscriptions.map(sub=><Link key={sub.id} href="/dashboard/customer/subscriptions" className={s.row}><div className={s.rowContent}><strong>{sub.product.name}</strong><small>{sub.store.name} · {sub.cancelAtPeriodEnd?"Ends after this period":sub.status.toLowerCase().replaceAll("_"," ")}{sub.sessionsRemaining!==null?` · ${sub.sessionsRemaining} sessions left`:""}</small></div><ArrowUpRight size={16}/></Link>)}</Panel>
   <Panel title="Saved for a little later" href="/wishlist" label={`${wishlist?._count.items??0} saved`}><div className={s.savedGrid}>{wishlist?.items.length?wishlist.items.map(item=><Link key={item.productId} href={item.product.isPublished&&!item.product.isArchived?`/${item.product.isService?"service":"products"}/${item.product.slug}`:"/wishlist"}><Thumb url={item.product.images[0]}><Heart size={24}/></Thumb><strong>{item.product.name}</strong><small>{item.product.isPublished&&!item.product.isArchived?money(Math.round(item.product.price*100)):"Currently unavailable"}</small></Link>):<Empty text="Tap the heart on a favourite find to keep it close." href="/shop" label="Find something to love"/>}</div></Panel>
  </div><aside className={s.stack}>
   <Panel title="Your good times" href="/my-tickets" id="tickets">{ticketEvents.length?ticketEvents.map(event=><Link className={s.row} href="/my-tickets" key={event.eventId}><Thumb><Ticket size={24}/></Thumb><div className={s.rowContent}><strong>{event.eventTitle}</strong><small>{formatEventDateShort(event.eventStartDate)} · {formatEventTime(event.eventStartDate)}</small><span className={s.badge}>{event.ticketCount} ticket{event.ticketCount===1?"":"s"}</span></div><ArrowUpRight size={17}/></Link>):<Empty text="A good time is better with a plan." href="/events" label="See what's happening"/>}</Panel>
   <Panel title="Conversations" href="/messages" label={unread?`${unread} unread`:"Open inbox"}>{conversations.length?conversations.map(c=><Link key={c.id} href={`/messages/${c.id}`} className={s.row}><Thumb url={c.storeLogoUrl}><MessageCircle size={22}/></Thumb><div className={s.rowContent}><strong>{c.storeName}</strong><small className={s.truncate}>{c.lastMessageText?.trim()||"Start the conversation"}</small><small>{formatConversationListTime(c.lastMessageAt)}</small></div>{c.unread>0&&<span className={s.dot} aria-label={`${c.unread} unread messages`}/>}</Link>):<Empty text="Questions, updates and conversations with local businesses will appear here."/>}</Panel>
   <Panel title="Latest updates" label={`${notificationCount} unread`}>{notifications.length?notifications.slice(0,3).map(n=>{const href=safeAccountHref(n.linkUrl);const content=<><Bell size={17}/><div className={s.rowContent}><strong>{n.title}</strong><small>{formatConversationListTime(n.createdAt)}</small></div>{!n.isRead&&<span className={s.dot} aria-label="Unread"/>}</>;return href?<Link href={href} className={s.row} key={n.id}>{content}</Link>:<div key={n.id} className={s.row}>{content}</div>;}):<Empty text="You're all caught up."/>}</Panel>
   <Panel title="Stores you love" href="/saved-stores" label={`${savedCount} saved`}>{savedStores.length?savedStores.map(({storeId,store})=><Link href={`/store/${store.slug}`} key={storeId} className={s.row}><Thumb url={store.logoUrl}><Bookmark size={22}/></Thumb><div className={s.rowContent}><strong>{store.name}</strong><small>Visit storefront</small></div><ArrowUpRight size={17}/></Link>):<Empty text="Keep your favourite local businesses close." href="/stores" label="Discover stores"/>}</Panel>
   {digitalOrders.length>0&&<Panel title="Your digital library" href="/orders">{digitalOrders.map(o=><Link href={`/orders/${o.id}`} key={o.id} className={s.row}><Download size={20}/><div className={s.rowContent}><strong>{o.items[0]?.titleSnapshot??"Digital order"}{o.items.length>1?` +${o.items.length-1} more`:""}</strong><small>Open your paid order to access downloads</small></div><ArrowUpRight size={16}/></Link>)}</Panel>}
  </aside></div><footer className={s.footer}>We people. We business. We local.</footer>
 </div></div>;
}
