"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState,useTransition } from "react";
import { acceptStaffInvitation } from "@/app/actions/staff-access";
export default function AcceptInvitation({token,email}:{token:string;email:string|null}){
 const router=useRouter(),[pending,start]=useTransition(),[error,setError]=useState("");
 return <section className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-8"><p className="text-xs uppercase tracking-widest text-slate-500">You’ve been invited</p><h1 className="my-4 text-3xl font-semibold">A place on the team.</h1><p className="mb-6 text-sm leading-7 text-slate-600">Use the email address your business owner invited. Once connected, you’ll see your assigned appointments, working hours and the tools your owner has enabled.</p>{email?<><p className="mb-4 text-sm">Signed in as <strong>{email}</strong></p><button className="rounded-xl bg-[#234954] px-6 py-3 text-sm font-semibold text-white disabled:opacity-50" disabled={pending} onClick={()=>start(async()=>{setError("");try{await acceptStaffInvitation(token);router.push("/team");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not accept invitation.");}})}>{pending?"Joining…":"Accept invitation"}</button><p className="mt-5 text-xs leading-6 text-slate-500">Verify your email through My account before accepting. If this is the wrong account, sign out there, then reopen this invitation.</p></>:<div className="space-y-4"><Link className="inline-block rounded-xl bg-[#234954] px-6 py-3 text-sm font-semibold text-white" href={`/login?callbackUrl=${encodeURIComponent(`/team/invite/${token}`)}`}>Sign in to join</Link><p className="text-sm text-slate-600">New to LinkWe? <Link className="underline" href="/register">Create a customer account</Link>, verify your email, then reopen this invitation.</p></div>}{error&&<p className="mt-5 text-sm text-red-700" role="alert">{error}</p>}</section>;
}
